'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { ArrowLeft, ArrowRight, Plus, Trash2, X } from 'lucide-react'
import { useAuth } from '@/components/auth-provider'
import { FundingNavigation } from '@/components/universities/funding-navigation'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { createManualFundingApplication } from '@/lib/universities/funding-domain'
import { getFundingOpportunity } from '@/lib/universities/funding-data'
import { universityStorage } from '@/lib/universities/storage'
import type { FundingApplication } from '@/lib/universities/types'

const label = (value: string) => value.toLowerCase().replace(/_/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())

export default function FundingApplicationsPage() {
  const { isGuest, settings, saveSettings } = useAuth()
  const [applications, setApplications] = useState<FundingApplication[]>([])
  const [showManual, setShowManual] = useState(false)
  const [manual, setManual] = useState({ name: '', provider: '', deadline: '', applicationUrl: '', expectedAmount: '', awardCurrency: '', notes: '' })
  useEffect(() => setApplications(isGuest ? universityStorage.getFundingApplications() : settings.fundingApplications), [isGuest, settings.fundingApplications])
  const persist = (next: FundingApplication[]) => { if (isGuest) universityStorage.saveFundingApplications(next); else void saveSettings({ fundingApplications: next }); setApplications(next) }
  const addManual = () => { if (!manual.name.trim() || !manual.provider.trim()) return; persist([...applications, createManualFundingApplication({ ...manual, expectedAmount: manual.expectedAmount ? Number(manual.expectedAmount) : undefined })]); setManual({ name: '', provider: '', deadline: '', applicationUrl: '', expectedAmount: '', awardCurrency: '', notes: '' }); setShowManual(false) }

  return <main className="mx-auto w-full max-w-5xl space-y-6 px-4 py-8 sm:px-6 lg:px-8">
    <Link href="/universities/funding" className="inline-flex items-center gap-2 text-sm font-medium text-sky-700"><ArrowLeft className="h-4 w-4" />Scholarships &amp; Funding</Link><FundingNavigation />
    <header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold text-slate-950">Funding applications</h1><p className="mt-2 text-slate-600">Track scholarship, bursary, government-support and learner-entered applications.</p></div><Button type="button" onClick={() => setShowManual((value) => !value)}>{showManual ? <X className="mr-2 h-4 w-4" /> : <Plus className="mr-2 h-4 w-4" />}{showManual ? 'Cancel' : 'Add funding'}</Button></header>
    {showManual ? <section className="border-y border-slate-200 bg-slate-50 p-5"><h2 className="text-lg font-semibold text-slate-950">Add a learner-entered opportunity</h2><p className="mt-1 text-sm text-slate-600">This stays separate from official canonical records.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Opportunity name<input value={manual.name} onChange={(event) => setManual({ ...manual, name: event.target.value })} className="mt-1 h-10 w-full rounded-md border border-slate-300 bg-white px-3" /></label><label className="text-sm font-medium text-slate-700">Provider<input value={manual.provider} onChange={(event) => setManual({ ...manual, provider: event.target.value })} className="mt-1 h-10 w-full rounded-md border border-slate-300 bg-white px-3" /></label><label className="text-sm font-medium text-slate-700">Personal deadline<input type="date" value={manual.deadline} onChange={(event) => setManual({ ...manual, deadline: event.target.value })} className="mt-1 h-10 w-full rounded-md border border-slate-300 bg-white px-3" /></label><label className="text-sm font-medium text-slate-700">Official application URL<input type="url" value={manual.applicationUrl} onChange={(event) => setManual({ ...manual, applicationUrl: event.target.value })} className="mt-1 h-10 w-full rounded-md border border-slate-300 bg-white px-3" /></label><label className="text-sm font-medium text-slate-700">Expected amount<input type="number" min="0" value={manual.expectedAmount} onChange={(event) => setManual({ ...manual, expectedAmount: event.target.value })} className="mt-1 h-10 w-full rounded-md border border-slate-300 bg-white px-3" /></label><label className="text-sm font-medium text-slate-700">Currency<input maxLength={3} value={manual.awardCurrency} onChange={(event) => setManual({ ...manual, awardCurrency: event.target.value.toUpperCase() })} className="mt-1 h-10 w-full rounded-md border border-slate-300 bg-white px-3" placeholder="AUD" /></label></div><Button type="button" className="mt-4" onClick={addManual}>Add to tracker</Button></section> : null}
    {!applications.length ? <Card className="p-6 text-sm text-slate-600">No funding applications yet. Browse indexed funding or add one manually.</Card> : <div className="space-y-4">{applications.map((application) => { const opportunity = application.fundingOpportunityId ? getFundingOpportunity(application.fundingOpportunityId) : undefined; const name = opportunity?.name || application.customOpportunityName || 'Untitled funding'; const provider = opportunity?.provider || application.customProvider || 'Provider not set'; return <Card key={application.id} className="p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold text-slate-950">{name}</h2><span className="rounded bg-slate-100 px-2 py-0.5 text-xs text-slate-600">{application.dataOrigin === 'USER_ENTERED' ? 'Learner entered' : 'Official record'}</span></div><p className="mt-1 text-sm text-slate-600">{provider} · {label(application.status)}</p></div><button type="button" onClick={() => persist(applications.filter((item) => item.id !== application.id))} aria-label={`Remove ${name}`} className="rounded-md p-2 text-slate-500 hover:bg-red-50 hover:text-red-700"><Trash2 className="h-4 w-4" /></button></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-600">Deadline: {application.deadlineOverride || opportunity?.applicationDeadline || 'Not indexed'}</p><Link href={`/universities/funding/applications/${application.id}`} className="inline-flex items-center gap-2 text-sm font-medium text-sky-700">Open application <ArrowRight className="h-4 w-4" /></Link></div></Card> })}</div>}
  </main>
}