import type { CountryCatalogue, Institution, Programme, SearchFilters, SearchResult } from './types'
import { COUNTRY_CATALOGUE_ADDITIONS, mergeCountryCatalogues } from './countries/expansion.ts'
import { deepenExistingInstitutions, PRIORITY_DEPTH_CATALOGUES } from './countries/priority-depth.ts'

export type { CountryCatalogue, Institution, Programme, SearchFilters, SearchResult } from './types'

const makeAliases = (...values: Array<string | string[] | undefined>) => Array.from(new Set(values.flatMap((value) => typeof value === 'string' ? [value] : value ?? []).map((value) => value.trim()).filter(Boolean)))

const SOUTH_AFRICAN_INSTITUTIONS: Institution[] = [
  { id: 'uct', name: 'University of Cape Town', aliases: makeAliases('UCT', 'Cape Town University'), institutionType: 'University', country: 'South Africa', code: 'ZA', region: 'Western Cape', city: 'Cape Town', officialWebsite: 'https://www.uct.ac.za/', admissionsUrl: 'https://uct.ac.za/study/undergraduate', publicPrivate: 'public', campusLocations: ['Cape Town'], studyAreas: ['Commerce', 'Engineering', 'Science', 'Health Sciences', 'Humanities', 'Law'], shortSummary: 'A major public research university in Cape Town with strong science, commerce, and health offerings.', sourceUrl: 'https://www.uct.ac.za/', lastVerifiedAt: '2026-09-01' },
  { id: 'wits', name: 'University of the Witwatersrand', aliases: makeAliases('Wits', 'Wits University'), institutionType: 'University', country: 'South Africa', code: 'ZA', region: 'Gauteng', city: 'Johannesburg', officialWebsite: 'https://www.wits.ac.za/', admissionsUrl: 'https://www.wits.ac.za/study-at-wits/undergraduate/', publicPrivate: 'public', campusLocations: ['Johannesburg'], studyAreas: ['Commerce', 'Engineering', 'Science', 'Health Sciences', 'Law', 'Humanities'], shortSummary: 'A leading Gauteng university with strong engineering, health, and commerce programmes.', sourceUrl: 'https://www.wits.ac.za/', lastVerifiedAt: '2026-09-01' },
  { id: 'up', name: 'University of Pretoria', aliases: makeAliases('UP', 'Tuks'), institutionType: 'University', country: 'South Africa', code: 'ZA', region: 'Gauteng', city: 'Pretoria', officialWebsite: 'https://www.up.ac.za/', admissionsUrl: 'https://www.up.ac.za/study-at-up', publicPrivate: 'public', campusLocations: ['Pretoria'], studyAreas: ['Commerce', 'Engineering', 'Science', 'Health Sciences', 'Law', 'Agriculture'], shortSummary: 'A major Gauteng institution with a broad range of science, commerce, law, and engineering offerings.', sourceUrl: 'https://www.up.ac.za/', lastVerifiedAt: '2026-09-01' },
  { id: 'stellenbosch', name: 'Stellenbosch University', aliases: makeAliases('SU', 'Stellenbosch'), institutionType: 'University', country: 'South Africa', code: 'ZA', region: 'Western Cape', city: 'Stellenbosch', officialWebsite: 'https://www.sun.ac.za/', admissionsUrl: 'https://www.sun.ac.za/english/Pages/default.aspx', publicPrivate: 'public', campusLocations: ['Stellenbosch', 'Tygerberg'], studyAreas: ['Commerce', 'Science', 'Engineering', 'Agriculture', 'Health Sciences', 'Humanities'], shortSummary: 'A leading South African university known for sciences, commerce, and agriculture.', sourceUrl: 'https://www.sun.ac.za/', lastVerifiedAt: '2026-09-01' },
  { id: 'uj', name: 'University of Johannesburg', aliases: makeAliases('UJ', 'UJ Johannesburg'), institutionType: 'University', country: 'South Africa', code: 'ZA', region: 'Gauteng', city: 'Johannesburg', officialWebsite: 'https://www.uj.ac.za/', admissionsUrl: 'https://www.uj.ac.za/studyatuj/', publicPrivate: 'public', campusLocations: ['Johannesburg'], studyAreas: ['Commerce', 'Engineering', 'Science', 'Humanities', 'Health Sciences'], shortSummary: 'A large metropolitan university with strong applied and business programmes.', sourceUrl: 'https://www.uj.ac.za/', lastVerifiedAt: '2026-09-01' },
  { id: 'ukzn', name: 'University of KwaZulu-Natal', aliases: makeAliases('UKZN'), institutionType: 'University', country: 'South Africa', code: 'ZA', region: 'KwaZulu-Natal', city: 'Durban', officialWebsite: 'https://www.ukzn.ac.za/', admissionsUrl: 'https://www.ukzn.ac.za/', publicPrivate: 'public', campusLocations: ['Durban', 'Pietermaritzburg'], studyAreas: ['Health Sciences', 'Science', 'Engineering', 'Humanities', 'Law'], shortSummary: 'A key KwaZulu-Natal university specialising in health sciences and engineering.', sourceUrl: 'https://www.ukzn.ac.za/', lastVerifiedAt: '2026-09-01' },
  { id: 'ufs', name: 'University of the Free State', aliases: makeAliases('UFS'), institutionType: 'University', country: 'South Africa', code: 'ZA', region: 'Free State', city: 'Bloemfontein', officialWebsite: 'https://www.ufs.ac.za/', admissionsUrl: 'https://www.ufs.ac.za/', publicPrivate: 'public', campusLocations: ['Bloemfontein'], studyAreas: ['Commerce', 'Science', 'Humanities', 'Health Sciences', 'Education'], shortSummary: 'A central Free State university with broad undergraduate and professional training.', sourceUrl: 'https://www.ufs.ac.za/', lastVerifiedAt: '2026-09-01' },
  { id: 'nwu', name: 'North-West University', aliases: makeAliases('NWU'), institutionType: 'University', country: 'South Africa', code: 'ZA', region: 'North West', city: 'Potchefstroom', officialWebsite: 'https://www.nwu.ac.za/', admissionsUrl: 'https://www.nwu.ac.za/', publicPrivate: 'public', campusLocations: ['Potchefstroom', 'Mahikeng', 'Vanderbijlpark'], studyAreas: ['Psychology', 'Business', 'Science', 'Humanities', 'Health Sciences'], shortSummary: 'A major multi-campus university in the North West and Gauteng regions.', sourceUrl: 'https://www.nwu.ac.za/', lastVerifiedAt: '2026-09-01' },
  { id: 'rhodes', name: 'Rhodes University', aliases: makeAliases('Rhodes'), institutionType: 'University', country: 'South Africa', code: 'ZA', region: 'Eastern Cape', city: 'Grahamstown', officialWebsite: 'https://www.ru.ac.za/', admissionsUrl: 'https://www.ru.ac.za/admissions/', publicPrivate: 'public', campusLocations: ['Grahamstown'], studyAreas: ['Humanities', 'Commerce', 'Science', 'Law'], shortSummary: 'A respected Eastern Cape institution with strong humanities and law offerings.', sourceUrl: 'https://www.ru.ac.za/', lastVerifiedAt: '2026-09-01' },
  { id: 'uwc', name: 'University of the Western Cape', aliases: makeAliases('UWC'), institutionType: 'University', country: 'South Africa', code: 'ZA', region: 'Western Cape', city: 'Bellville', officialWebsite: 'https://www.uwc.ac.za/', admissionsUrl: 'https://www.uwc.ac.za/study/', publicPrivate: 'public', campusLocations: ['Bellville'], studyAreas: ['Science', 'Social Sciences', 'Health Sciences', 'Education'], shortSummary: 'A Cape-based university with a strong public mission and social sciences profile.', sourceUrl: 'https://www.uwc.ac.za/', lastVerifiedAt: '2026-09-01' },
  { id: 'unisa', name: 'University of South Africa', aliases: makeAliases('UNISA'), institutionType: 'University', country: 'South Africa', code: 'ZA', region: 'Gauteng', city: 'Pretoria', officialWebsite: 'https://www.unisa.ac.za/', admissionsUrl: 'https://www.unisa.ac.za/sites/corporate/default/Apply-for-admission', publicPrivate: 'public', campusLocations: ['Pretoria'], studyAreas: ['Commerce', 'Education', 'Humanities', 'Law', 'Sciences'], shortSummary: 'South Africa’s open-distance learning institution with a large student base and broad programmes.', sourceUrl: 'https://www.unisa.ac.za/', lastVerifiedAt: '2026-09-01' },
  { id: 'tut', name: 'Tshwane University of Technology', aliases: makeAliases('TUT'), institutionType: 'University of Technology', country: 'South Africa', code: 'ZA', region: 'Gauteng', city: 'Pretoria', officialWebsite: 'https://www.tut.ac.za/', admissionsUrl: 'https://www.tut.ac.za/apply', publicPrivate: 'public', campusLocations: ['Pretoria', 'Johannesburg', 'Polokwane'], studyAreas: ['Engineering', 'Technology', 'Business', 'Applied Science'], shortSummary: 'A major university of technology focused on professional and applied fields.', sourceUrl: 'https://www.tut.ac.za/', lastVerifiedAt: '2026-09-01' },
  { id: 'cput', name: 'Cape Peninsula University of Technology', aliases: makeAliases('CPUT'), institutionType: 'University of Technology', country: 'South Africa', code: 'ZA', region: 'Western Cape', city: 'Cape Town', officialWebsite: 'https://www.cput.ac.za/', admissionsUrl: 'https://www.cput.ac.za/study', publicPrivate: 'public', campusLocations: ['Cape Town', 'Bellville'], studyAreas: ['Engineering', 'Technology', 'Business', 'Applied Science'], shortSummary: 'A technology-focused institution with strong engineering and applied science programmes.', sourceUrl: 'https://www.cput.ac.za/', lastVerifiedAt: '2026-09-01' },
  { id: 'dut', name: 'Durban University of Technology', aliases: makeAliases('DUT'), institutionType: 'University of Technology', country: 'South Africa', code: 'ZA', region: 'KwaZulu-Natal', city: 'Durban', officialWebsite: 'https://www.dut.ac.za/', admissionsUrl: 'https://www.dut.ac.za/applications', publicPrivate: 'public', campusLocations: ['Durban', 'Pietermaritzburg'], studyAreas: ['Engineering', 'Technology', 'Business', 'Applied Science'], shortSummary: 'A major Durban-based university of technology with applied technology strengths.', sourceUrl: 'https://www.dut.ac.za/', lastVerifiedAt: '2026-09-01' },
  { id: 'cut', name: 'Central University of Technology', aliases: makeAliases('CUT'), institutionType: 'University of Technology', country: 'South Africa', code: 'ZA', region: 'Free State', city: 'Bloemfontein', officialWebsite: 'https://www.cut.ac.za/', admissionsUrl: 'https://www.cut.ac.za/study', publicPrivate: 'public', campusLocations: ['Bloemfontein'], studyAreas: ['Engineering', 'Technology', 'Applied Science', 'Business'], shortSummary: 'A Free State university of technology with applied and engineering-oriented programmes.', sourceUrl: 'https://www.cut.ac.za/', lastVerifiedAt: '2026-09-01' },
  { id: 'vut', name: 'Vaal University of Technology', aliases: makeAliases('VUT'), institutionType: 'University of Technology', country: 'South Africa', code: 'ZA', region: 'Gauteng', city: 'Vanderbijlpark', officialWebsite: 'https://www.vut.ac.za/', admissionsUrl: 'https://www.vut.ac.za/', publicPrivate: 'public', campusLocations: ['Vanderbijlpark', 'Secunda'], studyAreas: ['Engineering', 'Technology', 'Business', 'Applied Science'], shortSummary: 'A technology-focused institution serving the Vaal and wider Gauteng region.', sourceUrl: 'https://www.vut.ac.za/', lastVerifiedAt: '2026-09-01' }
]

const AUSTRALIAN_INSTITUTIONS: Institution[] = [
  { id: 'unimelb', name: 'The University of Melbourne', aliases: makeAliases('UniMelb', 'Melbourne University'), institutionType: 'University', country: 'Australia', code: 'AU', region: 'Victoria', city: 'Melbourne', officialWebsite: 'https://www.unimelb.edu.au/', admissionsUrl: 'https://study.unimelb.edu.au/', publicPrivate: 'public', campusLocations: ['Parkville'], studyAreas: ['Commerce', 'Engineering', 'Science', 'Medicine', 'Psychology', 'Computer Science'], shortSummary: 'A major Victorian research university with a broad and highly regarded undergraduate portfolio.', sourceUrl: 'https://www.unimelb.edu.au/', lastVerifiedAt: '2026-09-01' },
  { id: 'monash', name: 'Monash University', aliases: makeAliases('Monash'), institutionType: 'University', country: 'Australia', code: 'AU', region: 'Victoria', city: 'Melbourne', officialWebsite: 'https://www.monash.edu/', admissionsUrl: 'https://www.monash.edu/study', publicPrivate: 'public', campusLocations: ['Clayton', 'Caulfield', 'Parkville'], studyAreas: ['Actuarial Science', 'Engineering', 'Business', 'Medicine', 'Computer Science', 'Science'], shortSummary: 'A major Melbourne university with strong actuarial, engineering, and business programmes.', sourceUrl: 'https://www.monash.edu/', lastVerifiedAt: '2026-09-01' },
  { id: 'unsw', name: 'UNSW Sydney', aliases: makeAliases('UNSW'), institutionType: 'University', country: 'Australia', code: 'AU', region: 'New South Wales', city: 'Sydney', officialWebsite: 'https://www.unsw.edu.au/', admissionsUrl: 'https://www.unsw.edu.au/study', publicPrivate: 'public', campusLocations: ['Kensington'], studyAreas: ['Engineering', 'Computer Science', 'Business', 'Science', 'Law'], shortSummary: 'A leading NSW university known for engineering, technology, and business.', sourceUrl: 'https://www.unsw.edu.au/', lastVerifiedAt: '2026-09-01' },
  { id: 'usyd', name: 'The University of Sydney', aliases: makeAliases('Sydney Uni', 'USyd'), institutionType: 'University', country: 'Australia', code: 'AU', region: 'New South Wales', city: 'Sydney', officialWebsite: 'https://www.sydney.edu.au/', admissionsUrl: 'https://www.sydney.edu.au/study.html', publicPrivate: 'public', campusLocations: ['Camperdown', 'Darlington'], studyAreas: ['Medicine', 'Business', 'Engineering', 'Science', 'Law', 'Arts'], shortSummary: 'A long-established NSW university with broad teaching and research strength.', sourceUrl: 'https://www.sydney.edu.au/', lastVerifiedAt: '2026-09-01' },
  { id: 'anu', name: 'Australian National University', aliases: makeAliases('ANU'), institutionType: 'University', country: 'Australia', code: 'AU', region: 'Australian Capital Territory', city: 'Canberra', officialWebsite: 'https://www.anu.edu.au/', admissionsUrl: 'https://www.anu.edu.au/study', publicPrivate: 'public', campusLocations: ['Canberra'], studyAreas: ['Engineering', 'Economics', 'Science', 'Politics', 'Computing'], shortSummary: 'A major Canberra-based research university with strong policy and science links.', sourceUrl: 'https://www.anu.edu.au/', lastVerifiedAt: '2026-09-01' },
  { id: 'uq', name: 'The University of Queensland', aliases: makeAliases('UQ'), institutionType: 'University', country: 'Australia', code: 'AU', region: 'Queensland', city: 'Brisbane', officialWebsite: 'https://www.uq.edu.au/', admissionsUrl: 'https://study.uq.edu.au/', publicPrivate: 'public', campusLocations: ['St Lucia'], studyAreas: ['Engineering', 'Science', 'Medicine', 'Business', 'Economics'], shortSummary: 'A major Queensland university with strong engineering and health programmes.', sourceUrl: 'https://www.uq.edu.au/', lastVerifiedAt: '2026-09-01' },
  { id: 'uts', name: 'University of Technology Sydney', aliases: makeAliases('UTS'), institutionType: 'University', country: 'Australia', code: 'AU', region: 'New South Wales', city: 'Sydney', officialWebsite: 'https://www.uts.edu.au/', admissionsUrl: 'https://www.uts.edu.au/study', publicPrivate: 'public', campusLocations: ['Ultimo'], studyAreas: ['Technology', 'Business', 'Design', 'Engineering', 'Computer Science'], shortSummary: 'A Sydney-based university of technology with strong applied and industry-linked courses.', sourceUrl: 'https://www.uts.edu.au/', lastVerifiedAt: '2026-09-01' },
  { id: 'rmit', name: 'RMIT University', aliases: makeAliases('RMIT'), institutionType: 'University', country: 'Australia', code: 'AU', region: 'Victoria', city: 'Melbourne', officialWebsite: 'https://www.rmit.edu.au/', admissionsUrl: 'https://www.rmit.edu.au/study-with-us', publicPrivate: 'public', campusLocations: ['Melbourne'], studyAreas: ['Design', 'Technology', 'Business', 'Engineering', 'Computer Science'], shortSummary: 'A large Melbourne institution with strong technology, design, and applied programmes.', sourceUrl: 'https://www.rmit.edu.au/', lastVerifiedAt: '2026-09-01' }
]

const UK_INSTITUTIONS: Institution[] = [
  { id: 'oxford', name: 'University of Oxford', aliases: makeAliases('Oxford'), institutionType: 'University', country: 'United Kingdom', code: 'GB', region: 'England', city: 'Oxford', officialWebsite: 'https://www.ox.ac.uk/', admissionsUrl: 'https://www.ox.ac.uk/admissions/undergraduate', publicPrivate: 'public', campusLocations: ['Oxford'], studyAreas: ['Humanities', 'Science', 'Engineering', 'Medicine', 'Law'], shortSummary: 'One of the world’s oldest and most prominent research universities.', sourceUrl: 'https://www.ox.ac.uk/', lastVerifiedAt: '2026-09-01' },
  { id: 'cambridge', name: 'University of Cambridge', aliases: makeAliases('Cambridge'), institutionType: 'University', country: 'United Kingdom', code: 'GB', region: 'England', city: 'Cambridge', officialWebsite: 'https://www.cam.ac.uk/', admissionsUrl: 'https://www.undergraduate.study.cam.ac.uk/', publicPrivate: 'public', campusLocations: ['Cambridge'], studyAreas: ['Science', 'Engineering', 'Humanities', 'Law', 'Medicine'], shortSummary: 'A major English university with broad academic depth and a strong research culture.', sourceUrl: 'https://www.cam.ac.uk/', lastVerifiedAt: '2026-09-01' },
  { id: 'lse', name: 'London School of Economics and Political Science', aliases: makeAliases('LSE'), institutionType: 'University', country: 'United Kingdom', code: 'GB', region: 'England', city: 'London', officialWebsite: 'https://www.lse.ac.uk/', admissionsUrl: 'https://www.lse.ac.uk/study-at-lse/undergraduate', publicPrivate: 'public', campusLocations: ['London'], studyAreas: ['Economics', 'Finance', 'Politics', 'Social Science', 'Law'], shortSummary: 'A leading London institution for economics, policy, and social sciences.', sourceUrl: 'https://www.lse.ac.uk/', lastVerifiedAt: '2026-09-01' },
  { id: 'imperial', name: 'Imperial College London', aliases: makeAliases('Imperial'), institutionType: 'University', country: 'United Kingdom', code: 'GB', region: 'England', city: 'London', officialWebsite: 'https://www.imperial.ac.uk/', admissionsUrl: 'https://www.imperial.ac.uk/study/undergraduate/', publicPrivate: 'public', campusLocations: ['London'], studyAreas: ['Engineering', 'Computer Science', 'Medicine', 'Science'], shortSummary: 'A leading London institution focused on science, engineering, and medicine.', sourceUrl: 'https://www.imperial.ac.uk/', lastVerifiedAt: '2026-09-01' },
  { id: 'ucl', name: 'University College London', aliases: makeAliases('UCL'), institutionType: 'University', country: 'United Kingdom', code: 'GB', region: 'England', city: 'London', officialWebsite: 'https://www.ucl.ac.uk/', admissionsUrl: 'https://www.ucl.ac.uk/prospective-students/undergraduate', publicPrivate: 'public', campusLocations: ['London'], studyAreas: ['Science', 'Engineering', 'Medicine', 'Law', 'Arts'], shortSummary: 'A large London university with wide academic coverage and strong research output.', sourceUrl: 'https://www.ucl.ac.uk/', lastVerifiedAt: '2026-09-01' },
  { id: 'edinburgh', name: 'University of Edinburgh', aliases: makeAliases('Edinburgh'), institutionType: 'University', country: 'United Kingdom', code: 'GB', region: 'Scotland', city: 'Edinburgh', officialWebsite: 'https://www.ed.ac.uk/', admissionsUrl: 'https://www.ed.ac.uk/studying/undergraduate', publicPrivate: 'public', campusLocations: ['Edinburgh'], studyAreas: ['Science', 'Computer Science', 'Psychology', 'Medicine', 'Humanities'], shortSummary: 'A major Scottish university with broad research and teaching strengths.', sourceUrl: 'https://www.ed.ac.uk/', lastVerifiedAt: '2026-09-01' },
  { id: 'cardiff', name: 'Cardiff University', aliases: makeAliases('Cardiff'), institutionType: 'University', country: 'United Kingdom', code: 'GB', region: 'Wales', city: 'Cardiff', officialWebsite: 'https://www.cardiff.ac.uk/', admissionsUrl: 'https://www.cardiff.ac.uk/study/undergraduate', publicPrivate: 'public', campusLocations: ['Cardiff'], studyAreas: ['Business', 'Science', 'Medicine', 'Law', 'Engineering'], shortSummary: 'A major Welsh university with strong study areas across science and business.', sourceUrl: 'https://www.cardiff.ac.uk/', lastVerifiedAt: '2026-09-01' },
  { id: 'queens-belfast', name: 'Queen’s University Belfast', aliases: makeAliases('Queen’s University Belfast', 'Queens University Belfast'), institutionType: 'University', country: 'United Kingdom', code: 'GB', region: 'Northern Ireland', city: 'Belfast', officialWebsite: 'https://www.qub.ac.uk/', admissionsUrl: 'https://www.qub.ac.uk/Study/', publicPrivate: 'public', campusLocations: ['Belfast'], studyAreas: ['Medicine', 'Engineering', 'Science', 'Law', 'Arts'], shortSummary: 'Northern Ireland’s leading research university with wide undergraduate offerings.', sourceUrl: 'https://www.qub.ac.uk/', lastVerifiedAt: '2026-09-01' }
]

const BASE_COUNTRY_CATALOGUE_DATA: CountryCatalogue[] = [
  { code: 'ZA', name: 'South Africa', region: 'Africa', status: 'substantial', institutions: SOUTH_AFRICAN_INSTITUTIONS, programmes: [
    { id: 'uct-bsc-cs', institutionId: 'uct', name: 'BSc Computer Science', normalizedName: 'computer science', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Science', department: 'Computer Science', studyAreas: ['Computer Science', 'Data Science'], tags: ['cs', 'technology'], campus: 'Cape Town', deliveryMode: 'On campus', duration: '3 years', officialProgrammeUrl: 'https://www.uct.ac.za/study/undergraduate', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official course page required for exact prerequisites.', sourceUrl: 'https://www.uct.ac.za/', lastVerifiedAt: '2026-09-01' },
    { id: 'uct-bcom-actuarial', institutionId: 'uct', name: 'BCom Actuarial Science', normalizedName: 'actuarial science', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Commerce', department: 'Actuarial Science', studyAreas: ['Actuarial Science', 'Finance', 'Analytics'], tags: ['actuarial', 'commerce'], campus: 'Cape Town', deliveryMode: 'On campus', duration: '3 years', officialProgrammeUrl: 'https://www.uct.ac.za/study/undergraduate', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official course page required for exact prerequisites.', sourceUrl: 'https://www.uct.ac.za/', lastVerifiedAt: '2026-09-01' },
    { id: 'uct-mbchb', institutionId: 'uct', name: 'MBChB Medicine', normalizedName: 'medicine', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Health Sciences', department: 'Medicine', studyAreas: ['Medicine', 'Health Sciences'], tags: ['medicine', 'health'], campus: 'Cape Town', deliveryMode: 'On campus', duration: '6 years', officialProgrammeUrl: 'https://www.uct.ac.za/study/undergraduate', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Biology', 'Chemistry', 'Mathematics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official course page required for exact prerequisites.', sourceUrl: 'https://www.uct.ac.za/', lastVerifiedAt: '2026-09-01' },
    { id: 'wits-bsc-cs', institutionId: 'wits', name: 'BSc Computer Science', normalizedName: 'computer science', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Science', department: 'Computer Science', studyAreas: ['Computer Science', 'Data Science'], tags: ['technology', 'cs'], campus: 'Johannesburg', deliveryMode: 'On campus', duration: '3 years', officialProgrammeUrl: 'https://www.wits.ac.za/study-at-wits/undergraduate/', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official course page required for exact prerequisites.', sourceUrl: 'https://www.wits.ac.za/', lastVerifiedAt: '2026-09-01' },
    { id: 'wits-bsc-engineering', institutionId: 'wits', name: 'BSc Engineering', normalizedName: 'engineering', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Engineering', department: 'Engineering', studyAreas: ['Engineering'], tags: ['engineering', 'stem'], campus: 'Johannesburg', deliveryMode: 'On campus', duration: '4 years', officialProgrammeUrl: 'https://www.wits.ac.za/study-at-wits/undergraduate/', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics', 'Physical Science'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official course page required for exact prerequisites.', sourceUrl: 'https://www.wits.ac.za/', lastVerifiedAt: '2026-09-01' },
    { id: 'up-bsc-cs', institutionId: 'up', name: 'BSc Computer Science', normalizedName: 'computer science', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Natural and Agricultural Sciences', department: 'Computer Science', studyAreas: ['Computer Science', 'Data Science'], tags: ['computer science', 'technology'], campus: 'Pretoria', deliveryMode: 'On campus', duration: '3 years', officialProgrammeUrl: 'https://www.up.ac.za/study-at-up', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official course page required for exact prerequisites.', sourceUrl: 'https://www.up.ac.za/', lastVerifiedAt: '2026-09-01' },
    { id: 'up-beng', institutionId: 'up', name: 'BEng Engineering', normalizedName: 'engineering', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Engineering', department: 'Engineering', studyAreas: ['Engineering'], tags: ['engineering', 'stem'], campus: 'Pretoria', deliveryMode: 'On campus', duration: '4 years', officialProgrammeUrl: 'https://www.up.ac.za/study-at-up', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics', 'Physical Science'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official course page required for exact prerequisites.', sourceUrl: 'https://www.up.ac.za/', lastVerifiedAt: '2026-09-01' },
    { id: 'stellenbosch-bsc-actuarial', institutionId: 'stellenbosch', name: 'BSc Actuarial Science', normalizedName: 'actuarial science', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Science', department: 'Actuarial Science', studyAreas: ['Actuarial Science', 'Statistics', 'Finance'], tags: ['actuarial', 'quantitative'], campus: 'Stellenbosch', deliveryMode: 'On campus', duration: '3 years', officialProgrammeUrl: 'https://www.sun.ac.za/', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics', 'Statistics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official course page required for exact prerequisites.', sourceUrl: 'https://www.sun.ac.za/', lastVerifiedAt: '2026-09-01' },
    { id: 'uj-bcom-accounting', institutionId: 'uj', name: 'BCom Accounting', normalizedName: 'accounting', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Commerce', department: 'Accounting', studyAreas: ['Accounting', 'Business'], tags: ['commerce', 'accounting'], campus: 'Johannesburg', deliveryMode: 'On campus', duration: '3 years', officialProgrammeUrl: 'https://www.uj.ac.za/studyatuj/', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official course page required for exact prerequisites.', sourceUrl: 'https://www.uj.ac.za/', lastVerifiedAt: '2026-09-01' },
    { id: 'ukzn-mbchb', institutionId: 'ukzn', name: 'MBChB Medicine', normalizedName: 'medicine', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Health Sciences', department: 'Medicine', studyAreas: ['Medicine', 'Health Sciences'], tags: ['health', 'medicine'], campus: 'Durban', deliveryMode: 'On campus', duration: '6 years', officialProgrammeUrl: 'https://www.ukzn.ac.za/', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Biology', 'Chemistry'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official course page required for exact prerequisites.', sourceUrl: 'https://www.ukzn.ac.za/', lastVerifiedAt: '2026-09-01' },
    { id: 'nwu-bpsych', institutionId: 'nwu', name: 'BPsychology', normalizedName: 'psychology', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Humanities', department: 'Psychology', studyAreas: ['Psychology', 'Social Sciences'], tags: ['psychology', 'humanities'], campus: 'Potchefstroom', deliveryMode: 'On campus', duration: '4 years', officialProgrammeUrl: 'https://www.nwu.ac.za/', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['English', 'Mathematics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official course page required for exact prerequisites.', sourceUrl: 'https://www.nwu.ac.za/', lastVerifiedAt: '2026-09-01' },
    { id: 'unisa-bcom', institutionId: 'unisa', name: 'BCom', normalizedName: 'commerce', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Commerce', department: 'Business', studyAreas: ['Commerce', 'Business'], tags: ['commerce', 'business'], campus: 'Pretoria', deliveryMode: 'Distance / blended', duration: '3 years', officialProgrammeUrl: 'https://www.unisa.ac.za/', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official course page required for exact prerequisites.', sourceUrl: 'https://www.unisa.ac.za/', lastVerifiedAt: '2026-09-01' },
    { id: 'tut-btech-engineering', institutionId: 'tut', name: 'BTech Engineering', normalizedName: 'engineering', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Engineering and the Built Environment', department: 'Engineering', studyAreas: ['Engineering', 'Technology'], tags: ['engineering', 'applied'], campus: 'Pretoria', deliveryMode: 'On campus', duration: '4 years', officialProgrammeUrl: 'https://www.tut.ac.za/', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics', 'Physical Science'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official course page required for exact prerequisites.', sourceUrl: 'https://www.tut.ac.za/', lastVerifiedAt: '2026-09-01' },
    { id: 'cput-beng', institutionId: 'cput', name: 'BEng Technology', normalizedName: 'engineering', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Engineering', department: 'Engineering', studyAreas: ['Engineering', 'Technology'], tags: ['engineering', 'applied'], campus: 'Cape Town', deliveryMode: 'On campus', duration: '4 years', officialProgrammeUrl: 'https://www.cput.ac.za/', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics', 'Physical Science'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official course page required for exact prerequisites.', sourceUrl: 'https://www.cput.ac.za/', lastVerifiedAt: '2026-09-01' },
    { id: 'dut-diploma-engineering', institutionId: 'dut', name: 'Diploma in Engineering', normalizedName: 'engineering', degreeType: 'Diploma', qualificationLevel: 'Undergraduate', faculty: 'Engineering', department: 'Engineering', studyAreas: ['Engineering', 'Technology'], tags: ['engineering', 'diploma'], campus: 'Durban', deliveryMode: 'On campus', duration: '3 years', officialProgrammeUrl: 'https://www.dut.ac.za/', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics', 'Physical Science'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official course page required for exact prerequisites.', sourceUrl: 'https://www.dut.ac.za/', lastVerifiedAt: '2026-09-01' }
  ] },
  { code: 'AU', name: 'Australia', region: 'Oceania', status: 'substantial', institutions: AUSTRALIAN_INSTITUTIONS, programmes: [
    { id: 'unimelb-bsc-comp-sci', institutionId: 'unimelb', name: 'Bachelor of Science - Computer Science', normalizedName: 'computer science', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Science', department: 'Computing and Information Systems', studyAreas: ['Computer Science', 'Data Science'], tags: ['computer science', 'technology'], campus: 'Parkville', deliveryMode: 'On campus', duration: '3 years', officialProgrammeUrl: 'https://study.unimelb.edu.au/', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official requirements vary by intake and curriculum.', sourceUrl: 'https://study.unimelb.edu.au/', lastVerifiedAt: '2026-09-01' },
    { id: 'unimelb-bcom-econ', institutionId: 'unimelb', name: 'Bachelor of Commerce - Economics', normalizedName: 'economics', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Business and Economics', department: 'Economics', studyAreas: ['Economics', 'Finance'], tags: ['economics', 'commerce'], campus: 'Parkville', deliveryMode: 'On campus', duration: '3 years', officialProgrammeUrl: 'https://study.unimelb.edu.au/', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official requirements vary by intake and curriculum.', sourceUrl: 'https://study.unimelb.edu.au/', lastVerifiedAt: '2026-09-01' },
    { id: 'monash-actuarial', institutionId: 'monash', name: 'Bachelor of Actuarial Science', normalizedName: 'actuarial science', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Business and Economics', department: 'Actuarial Studies', studyAreas: ['Actuarial Science', 'Risk', 'Analytics'], tags: ['actuarial', 'finance'], campus: 'Clayton', deliveryMode: 'On campus', duration: '3 years', officialProgrammeUrl: 'https://www.monash.edu/study/courses/find-a-course', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official requirements vary by intake and curriculum.', sourceUrl: 'https://www.monash.edu/', lastVerifiedAt: '2026-09-01' },
    { id: 'monash-beng', institutionId: 'monash', name: 'Bachelor of Engineering', normalizedName: 'engineering', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Engineering', department: 'Engineering', studyAreas: ['Engineering'], tags: ['engineering', 'stem'], campus: 'Clayton', deliveryMode: 'On campus', duration: '4 years', officialProgrammeUrl: 'https://www.monash.edu/study/courses/find-a-course', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics', 'Physics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official requirements vary by intake and curriculum.', sourceUrl: 'https://www.monash.edu/', lastVerifiedAt: '2026-09-01' },
    { id: 'unsw-bsc-compsci', institutionId: 'unsw', name: 'Bachelor of Science (Computer Science)', normalizedName: 'computer science', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Engineering', department: 'Computer Science', studyAreas: ['Computer Science', 'Engineering'], tags: ['computer science', 'technology'], campus: 'Kensington', deliveryMode: 'On campus', duration: '3 years', officialProgrammeUrl: 'https://www.unsw.edu.au/study', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official requirements vary by intake and curriculum.', sourceUrl: 'https://www.unsw.edu.au/', lastVerifiedAt: '2026-09-01' },
    { id: 'usyd-mbbs', institutionId: 'usyd', name: 'MBBS Medicine', normalizedName: 'medicine', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Medicine and Health', department: 'Medicine', studyAreas: ['Medicine', 'Health Sciences'], tags: ['medicine', 'health'], campus: 'Camperdown', deliveryMode: 'On campus', duration: '6 years', officialProgrammeUrl: 'https://www.sydney.edu.au/study.html', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Biology', 'Chemistry'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official requirements vary by intake and curriculum.', sourceUrl: 'https://www.sydney.edu.au/', lastVerifiedAt: '2026-09-01' },
    { id: 'anu-bsc-cs', institutionId: 'anu', name: 'Bachelor of Science (Computer Science)', normalizedName: 'computer science', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Science', department: 'Computer Science', studyAreas: ['Computer Science', 'Data Science'], tags: ['computer science', 'technology'], campus: 'Canberra', deliveryMode: 'On campus', duration: '3 years', officialProgrammeUrl: 'https://www.anu.edu.au/study', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official requirements vary by intake and curriculum.', sourceUrl: 'https://www.anu.edu.au/', lastVerifiedAt: '2026-09-01' },
    { id: 'uq-bachelor-of-economics', institutionId: 'uq', name: 'Bachelor of Economics', normalizedName: 'economics', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Business, Economics and Law', department: 'Economics', studyAreas: ['Economics', 'Business'], tags: ['economics', 'business'], campus: 'St Lucia', deliveryMode: 'On campus', duration: '3 years', officialProgrammeUrl: 'https://study.uq.edu.au/', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official requirements vary by intake and curriculum.', sourceUrl: 'https://www.uq.edu.au/', lastVerifiedAt: '2026-09-01' }
  ] },
  { code: 'GB', name: 'United Kingdom', region: 'Europe', status: 'substantial', institutions: UK_INSTITUTIONS, programmes: [
    { id: 'oxford-maths', institutionId: 'oxford', name: 'Mathematics', normalizedName: 'mathematics', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Mathematical, Physical and Life Sciences', department: 'Mathematics', studyAreas: ['Mathematics', 'Science'], tags: ['maths', 'science'], campus: 'Oxford', deliveryMode: 'On campus', duration: '3 years', officialProgrammeUrl: 'https://www.ox.ac.uk/admissions/undergraduate', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official requirements vary by intake and curriculum.', sourceUrl: 'https://www.ox.ac.uk/', lastVerifiedAt: '2026-09-01' },
    { id: 'cambridge-engineering', institutionId: 'cambridge', name: 'Engineering', normalizedName: 'engineering', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Engineering', department: 'Engineering', studyAreas: ['Engineering'], tags: ['engineering', 'stem'], campus: 'Cambridge', deliveryMode: 'On campus', duration: '3 years', officialProgrammeUrl: 'https://www.undergraduate.study.cam.ac.uk/', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics', 'Physics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official requirements vary by intake and curriculum.', sourceUrl: 'https://www.cam.ac.uk/', lastVerifiedAt: '2026-09-01' },
    { id: 'lse-economics', institutionId: 'lse', name: 'BSc Economics', normalizedName: 'economics', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Social Sciences', department: 'Economics', studyAreas: ['Economics', 'Social Science'], industryAreas: ['Finance', 'Policy'], tags: ['economics', 'policy'], campus: 'London', deliveryMode: 'On campus', duration: '3 years', officialProgrammeUrl: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-economics', admissionsUrl: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-economics', curriculumRequirements: ['IB Diploma: 39 points overall, with 766 at Higher Level and 7 in Mathematics.'], requirements: [{ curriculum: 'IB', minimumOverall: 39, requiredSubjects: [{ name: 'Mathematics', level: 'HL', minimumGrade: '7' }], admissionsCycle: '2026', notes: 'Standard IB offer; contextual offer information is published separately by LSE.', officialRequirementsUrl: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-economics', sourceType: 'official-programme', lastVerifiedAt: '2026-09-09' }], standardisedTests: ['TMUA (mandatory for applicants)'], prerequisiteSubjects: ['Mathematics'], entryRequirements: ['IB Diploma: 39 points overall; 766 at Higher Level with 7 in Mathematics.', 'TMUA required'], applicationMetadata: 'Admission is competitive; meeting published requirements does not guarantee an offer.', admissionsCycle: '2026', sourceUrl: 'https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-economics', sourceType: 'official-programme', lastVerifiedAt: '2026-09-09' },
    { id: 'imperial-cs', institutionId: 'imperial', name: 'BEng / MEng Computer Science', normalizedName: 'computer science', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Engineering', department: 'Computing', studyAreas: ['Computer Science', 'Engineering'], tags: ['computer science', 'technology'], campus: 'London', deliveryMode: 'On campus', duration: '3-4 years', officialProgrammeUrl: 'https://www.imperial.ac.uk/study/undergraduate/', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official requirements vary by intake and curriculum.', sourceUrl: 'https://www.imperial.ac.uk/', lastVerifiedAt: '2026-09-01' },
    { id: 'edinburgh-psych', institutionId: 'edinburgh', name: 'BSc Psychology', normalizedName: 'psychology', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Science and Engineering', department: 'Psychology', studyAreas: ['Psychology', 'Science'], tags: ['psychology', 'social science'], campus: 'Edinburgh', deliveryMode: 'On campus', duration: '4 years', officialProgrammeUrl: 'https://www.ed.ac.uk/studying/undergraduate', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Biology', 'Mathematics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official requirements vary by intake and curriculum.', sourceUrl: 'https://www.ed.ac.uk/', lastVerifiedAt: '2026-09-01' },
    { id: 'cardiff-commerce', institutionId: 'cardiff', name: 'BSc Economics and Finance', normalizedName: 'economics', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Business', department: 'Economics and Finance', studyAreas: ['Economics', 'Finance'], tags: ['economics', 'finance'], campus: 'Cardiff', deliveryMode: 'On campus', duration: '3 years', officialProgrammeUrl: 'https://www.cardiff.ac.uk/study/undergraduate', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Mathematics'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official requirements vary by intake and curriculum.', sourceUrl: 'https://www.cardiff.ac.uk/', lastVerifiedAt: '2026-09-01' },
    { id: 'queens-medicine', institutionId: 'queens-belfast', name: 'MBBS Medicine', normalizedName: 'medicine', degreeType: 'Bachelor', qualificationLevel: 'Undergraduate', faculty: 'Medicine, Health and Life Sciences', department: 'Medicine', studyAreas: ['Medicine', 'Health Sciences'], tags: ['medicine', 'health'], campus: 'Belfast', deliveryMode: 'On campus', duration: '5 years', officialProgrammeUrl: 'https://www.qub.ac.uk/Study/', curriculumRequirements: ['Check official requirements'], prerequisiteSubjects: ['Biology', 'Chemistry'], entryRequirements: ['Check official entry requirements'], applicationMetadata: 'Official requirements vary by intake and curriculum.', sourceUrl: 'https://www.qub.ac.uk/', lastVerifiedAt: '2026-09-01' }
  ] }
]

const COUNTRY_CATALOGUE_DATA = deepenExistingInstitutions(mergeCountryCatalogues(BASE_COUNTRY_CATALOGUE_DATA, [...COUNTRY_CATALOGUE_ADDITIONS, ...PRIORITY_DEPTH_CATALOGUES]))

export const COUNTRY_OPTIONS = ['All', ...COUNTRY_CATALOGUE_DATA.map((country) => country.name)]
export const REGION_OPTIONS = ['All', ...Array.from(new Set(COUNTRY_CATALOGUE_DATA.flatMap((country) => country.institutions.map((institution) => institution.region)))).sort()]
export const STUDY_AREA_OPTIONS = ['All', ...Array.from(new Set(COUNTRY_CATALOGUE_DATA.flatMap((country) => country.programmes.flatMap((programme) => programme.studyAreas)))).sort()]
export const QUALIFICATION_OPTIONS = ['All', ...Array.from(new Set(COUNTRY_CATALOGUE_DATA.flatMap((country) => country.programmes.map((programme) => programme.degreeType)))).sort()]

export function getCountryCatalogue(codeOrName: string): CountryCatalogue | undefined {
  const normalized = codeOrName.trim().toLowerCase()
  return COUNTRY_CATALOGUE_DATA.find((country) => country.code.toLowerCase() === normalized || country.name.toLowerCase() === normalized)
}

export function normalizeUniversityQuery(value: string) {
  return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/&/g, ' and ').replace(/[^a-z0-9\s]/g, ' ').replace(/\s+/g, ' ').trim()
}

const SEARCH_SYNONYMS: Record<string, string> = {
  'comp sci': 'computer science',
  computing: 'computer science',
  econ: 'economics',
  actuar: 'actuarial',
  med: 'medicine'
}

function expandSearchQuery(value: string) {
  const normalized = normalizeUniversityQuery(value)
  return SEARCH_SYNONYMS[normalized] ?? normalized
}

export function flattenSearchRecords() {
  return COUNTRY_CATALOGUE_DATA.flatMap((country) => country.programmes.map((programme) => {
    const institution = country.institutions.find((entry) => entry.id === programme.institutionId)
    return institution ? { country: country.name, region: institution.region, institution, programme } as SearchResult : null
  })).filter(Boolean) as SearchResult[]
}

function scoreMatch(query: string, institution: Institution, programme: Programme) {
  const normalized = expandSearchQuery(query)
  const institutionIdentity = normalizeUniversityQuery([
    institution.name,
    institution.aliases.join(' '),
  ].join(' '))
  const programmeIdentity = normalizeUniversityQuery([
    programme.name,
    programme.normalizedName,
    ...(programme.aliases ?? []),
  ].join(' '))
  const programmeContext = normalizeUniversityQuery([
    programme.studyAreas.join(' '),
    programme.faculty,
    programme.department ?? '',
    ...programme.tags
  ].join(' '))
  const location = normalizeUniversityQuery([institution.city, institution.region, institution.country].join(' '))

  if (!normalized) return 0
  if (programmeIdentity === normalized || programme.normalizedName === normalized) return 120
  if (programmeIdentity.includes(normalized)) return 110
  if (programmeContext.includes(normalized)) return 90
  if (institution.aliases.some((alias) => normalizeUniversityQuery(alias) === normalized)) return 85
  if (institutionIdentity.includes(normalized)) return 80
  if (location.includes(normalized)) return 40

  const tokens = normalized.split(' ').filter((token) => token.length > 1)
  if (tokens.length && tokens.every((token) => programmeIdentity.includes(token))) return 100
  if (tokens.length && tokens.every((token) => programmeContext.includes(token))) return 75
  if (tokens.length && tokens.every((token) => institutionIdentity.includes(token))) return 65
  if (tokens.length && tokens.every((token) => location.includes(token))) return 30
  return 0
}

export function searchUniversityCatalogue(query: string, filters: SearchFilters = {}) {
  const safeQuery = expandSearchQuery(query)
  const results = flattenSearchRecords().filter((record) => {
    const institution = record.institution
    const programme = record.programme

    if (filters.country && filters.country !== 'All' && record.country !== filters.country) return false
    if (filters.region && filters.region !== 'All' && record.region !== filters.region) return false
    if (filters.institutionType && filters.institutionType !== 'All' && institution.institutionType !== filters.institutionType) return false
    if (filters.studyArea && filters.studyArea !== 'All' && !programme.studyAreas.some((area) => area.toLowerCase() === filters.studyArea!.toLowerCase())) return false
    if (filters.qualification && filters.qualification !== 'All' && programme.degreeType !== filters.qualification) return false

    if (!safeQuery) return true

    return scoreMatch(safeQuery, institution, programme) > 0
  })

  return results
    .map((record) => ({ ...record, score: scoreMatch(safeQuery || record.programme.name, record.institution, record.programme) }))
    .sort((left, right) => right.score - left.score)
}

export function getCountryFilters() {
  return COUNTRY_CATALOGUE_DATA.map((country) => ({
    code: country.code,
    name: country.name,
    institutionCount: country.institutions.length,
    programmeCount: country.programmes.length,
    status: country.status,
    coverage: getCountryCoverage(country)
  }))
}

export function getCountryCoverage(country: CountryCatalogue) {
  const programmesPerInstitution = country.institutions.length ? country.programmes.length / country.institutions.length : 0
  const sourcedProgrammes = country.programmes.filter((programme) => programme.sourceType && programme.lastCheckedAt).length
  const structuredAdmissions = country.programmes.filter((programme) => programme.requirements?.length).length
  const programmeCoverage = programmesPerInstitution >= 10 ? 'substantial' : programmesPerInstitution >= 4 ? 'partial' : 'building'
  const admissionsCoverage = structuredAdmissions / Math.max(country.programmes.length, 1) >= 0.5 ? 'substantial' : structuredAdmissions ? 'partial' : 'building'
  const sourceFreshness = sourcedProgrammes / Math.max(country.programmes.length, 1) >= 0.8 ? 'substantial' : 'partial'
  return {
    institutionCoverage: country.institutions.length >= 20 ? 'substantial' : country.institutions.length >= 10 ? 'partial' : 'building',
    programmeCoverage,
    admissionsCoverage,
    sourceFreshness,
    overall: programmeCoverage === 'substantial' && admissionsCoverage === 'substantial' ? 'substantial' : 'partial'
  } as const
}

export function getInstitution(institutionId: string) {
  for (const country of COUNTRY_CATALOGUE_DATA) {
    const institution = country.institutions.find((entry) => entry.id === institutionId)
    if (institution) return institution
  }
  return undefined
}

export function getProgramme(programmeId: string) {
  for (const country of COUNTRY_CATALOGUE_DATA) {
    const programme = country.programmes.find((entry) => entry.id === programmeId)
    if (programme) return programme
  }
  return undefined
}

export function getInstitutionProgrammes(institutionId: string) {
  return COUNTRY_CATALOGUE_DATA.flatMap((country) => country.programmes).filter((programme) => programme.institutionId === institutionId)
}
