import type { FundingOpportunity } from './types.ts'

const CHECKED_AT = '2026-09-10T00:00:00Z'

type FundingSeed = Pick<FundingOpportunity,
  'id' | 'name' | 'provider' | 'providerType' | 'fundingType' | 'providerCountry' |
  'eligibleDestinationCountries' | 'domesticInternationalRules' | 'amountType' |
  'coverage' | 'officialUrl' | 'fundingCycle' | 'cycleStatus' | 'active'
> & Partial<FundingOpportunity>

function officialFunding(seed: FundingSeed): FundingOpportunity {
  return {
    repaymentType: 'NON_REPAYABLE',
    eligibleInstitutions: [],
    eligibleProgrammes: [],
    eligibleFaculties: [],
    eligibleStudyAreas: [],
    eligibleStudyLevels: ['SCHOOL_LEAVER', 'BACHELOR', 'CURRENT_UNIVERSITY'],
    citizenshipRules: [],
    residenceRules: [],
    applicantRouteRules: [],
    curriculumRules: [],
    academicRequirements: [],
    otherEligibility: [],
    separateApplicationRequired: true,
    applicationMethod: 'Apply through the official provider page and follow the current cycle instructions.',
    applicationUrl: seed.officialUrl,
    sourceUrl: seed.officialUrl,
    sourceType: 'official-scholarship',
    sourceTitle: seed.name,
    lastCheckedAt: CHECKED_AT,
    lastVerifiedAt: CHECKED_AT,
    confidenceStatus: 'VERIFIED_OFFICIAL',
    ...seed
  }
}

type SouthAfricaSeed = {
  id: string
  name: string
  provider: string
  eligibility: string[]
  coverage: string[]
  url: string
  areas?: string[]
}

const SOUTH_AFRICA_SEEDS: SouthAfricaSeed[] = [
  { id: 'za-amazon-recruitment-2027', name: 'Amazon Recruitment Bursary', provider: 'Amazon', eligibility: ['South African citizen in the final undergraduate year in 2027', 'Computer science, computer or software engineering, machine learning or artificial intelligence', 'At least 65%; NQF 8 progression and work-back conditions apply'], coverage: ['Tuition', 'Accommodation', 'Subsistence', 'Books', 'Computer', 'Transport'], areas: ['Computer Science', 'Software Engineering', 'Artificial Intelligence'], url: 'https://studytrust.org.za/amazon-recruitment-bursaries/' },
  { id: 'za-standard-bank-undergraduate-2027', name: 'Standard Bank Group Undergraduate Bursary', provider: 'Standard Bank Group', eligibility: ['South African citizen in second through final undergraduate year', 'At least 65% and demonstrated financial need'], coverage: ['Tuition', 'Accommodation', 'Meals', 'Study materials', 'Laptop', 'Stipend', 'Limited travel'], url: 'https://studytrust.org.za/standardbank/' },
  { id: 'za-santam-2027', name: 'Santam Bursary Programme', provider: 'Santam', eligibility: ['South African citizen in second, third or final undergraduate year or honours', 'At least 65% in a published eligible field'], coverage: ['Capped tuition', 'Accommodation', 'Study materials', 'Laptop', 'Monthly allowance', 'Transport allowance'], areas: ['Actuarial Science', 'Data Science', 'Agriculture', 'Engineering', 'Finance', 'Risk Management'], url: 'https://studytrust.org.za/santam/' },
  { id: 'za-toyota-motors-2027', name: 'Toyota SA Motors Bursary', provider: 'Toyota South Africa Motors', eligibility: ['South African citizen studying full-time in a listed commerce, engineering or science field', 'At least 65% in Mathematics, English and tertiary studies'], coverage: ['Bursary support; fixed value not published'], url: 'https://studytrust.org.za/toyota/' },
  { id: 'za-amazon-operations-2027', name: 'Amazon Operations Bursary', provider: 'Amazon', eligibility: ['South African citizen in a final four-year degree or honours year in 2027', 'At least 70% in an eligible operations, logistics, engineering, analytics, statistics or finance field'], coverage: ['Capped tuition', 'Accommodation', 'Subsistence', 'Books', 'Computer'], url: 'https://studytrust.org.za/amazon-operations-bursary/' },
  { id: 'za-cisco-charitable-foundation-2027', name: 'Cisco Charitable Foundation Trust South Africa Bursary', provider: 'Cisco Charitable Foundation Trust South Africa', eligibility: ['South African citizen in first through fourth year of a computing or information technology field', 'Published household-income and equity criteria apply'], coverage: ['Award value not published'], areas: ['Computer Science', 'Information Technology'], url: 'https://studytrust.org.za/the-cisco-charitable-foundation-trust-south-africa-bursary-programme/' },
  { id: 'za-imfundo-trust-2027', name: 'Old Mutual Investment Group Imfundo Trust Scholarship', provider: 'Old Mutual Investment Group Imfundo Trust', eligibility: ['South African citizen in first or second year in 2027', 'Published academic, field and community criteria apply'], coverage: ['Full-time study funding; fixed value not published'], url: 'https://studytrust.org.za/old-mutual/' },
  { id: 'za-promaths-2027', name: 'Promaths Bursary', provider: 'Promaths', eligibility: ['South African Promaths or Kutlwanong alumnus', 'Accepted for a rare-skills degree or national diploma', 'Academic merit and financial need'], coverage: ['Variable bursary support'], url: 'https://studytrust.org.za/promaths/' },
  { id: 'za-investec-csi-2027', name: 'Investec CSI Bursary', provider: 'Investec', eligibility: ['South African citizen in Grade 12, a post-Grade-12 gap year, or first university year', 'Eligible commerce, STEM, commercial law or medicine field', 'Academic merit and financial need'], coverage: ['Full-cost bursary support'], url: 'https://studytrust.org.za/investec/' },
  { id: 'za-firstrand-empowerment-2027', name: 'FirstRand Empowerment Foundation Undergraduate Bursary', provider: 'FirstRand Empowerment Foundation', eligibility: ['Black South African citizen starting a first degree in 2027', 'Published age, income and Mathematics thresholds apply'], coverage: ['Tuition', 'Accommodation', 'Meals', 'Study resources', 'Stipend', 'First-year computer'], url: 'https://studytrust.org.za/fref-bursary/' },
  { id: 'za-aws-skills-development-2027', name: 'AWS Skills Development Bursary', provider: 'Amazon Web Services', eligibility: ['South African citizen in first through final year in a listed field', 'Academic merit and financial need; generally at least 65%'], coverage: ['Capped tuition', 'Accommodation', 'Subsistence', 'Books', 'Computer'], url: 'https://studytrust.org.za/amazon-web/' },
  { id: 'za-hp-inc-2027', name: 'HP Inc Bursary', provider: 'HP Inc', eligibility: ['South African citizen studying undergraduate Computer Science or Engineering at a public institution', 'At least 65%'], coverage: ['Award value not published'], areas: ['Computer Science', 'Engineering'], url: 'https://studytrust.org.za/hp-inc-bursaries/' },
  { id: 'za-sage-external-2027', name: 'Sage External Bursary', provider: 'Sage', eligibility: ['South African citizen from a previously disadvantaged group', 'Public institution student in information technology, accounting or computer science', 'Published academic and household-income rules apply'], coverage: ['Capped tuition', 'Accommodation', 'Stationery', 'Allowance', 'Laptop', 'Eligible historical debt'], url: 'https://studytrust.org.za/sage/' },
  { id: 'za-dec-trust-disability-2027', name: 'DEC Trust Bursary for Students with Disabilities', provider: 'DEC Trust', eligibility: ['South African citizen with a verified disability', 'Approved scarce-skills field at a public university', 'No concurrent funding; generally at least 65%'], coverage: ['Tuition', 'Accommodation', 'Books', 'Living allowance', 'Laptop', 'Disability support'], url: 'https://studytrust.org.za/dec-trust/' },
  { id: 'za-globeleq-educational-trust-2027', name: 'Globeleq Educational Trust Bursary', provider: 'Globeleq Educational Trust', eligibility: ['Female South African applicant studying STEM at a public institution', 'Merit and financial need; Western Cape school-leaver preference applies'], coverage: ['Individually determined tuition', 'Registration', 'Accommodation', 'Meals', 'Study materials'], areas: ['Science', 'Technology', 'Engineering', 'Mathematics'], url: 'https://studytrust.org.za/globeleq-educational-trust' },
  { id: 'za-aurora-wind-power-2027', name: 'Aurora Wind Power Bursary', provider: 'Aurora Wind Power', eligibility: ['South African Grade 12 learner from a designated West Coast school', 'Public three- or four-year degree and published household-income limit'], coverage: ['Individually determined tuition', 'Registration', 'Accommodation', 'Meals', 'Study materials'], url: 'https://studytrust.org.za/aurora-wind-power' },
  { id: 'za-kathu-solar-park-2027', name: 'Kathu Solar Park Bursary', provider: 'Kathu Solar Park', eligibility: ['South African citizen residing in Kathu or John Taolo Gaetsewe District', 'Commencing or current full-time student meeting the published household-income limit'], coverage: ['Individually determined tuition', 'Registration', 'Accommodation', 'Meals', 'Study materials'], url: 'https://studytrust.org.za/kathu-solar-park/' },
  { id: 'za-sishen-solar-facility-2027', name: 'Sishen Solar Facility Bursary', provider: 'Sishen Solar Facility', eligibility: ['Previously disadvantaged South African applicant from a designated local school', 'Current or previous Grade 12 learner entering a public institution'], coverage: ['Individually determined tuition', 'Registration', 'Accommodation', 'Meals', 'Study materials'], url: 'https://studytrust.org.za/sishen-solar-facility' },
  { id: 'za-enel-green-power-2027', name: 'Enel Green Power RSA Bursary Programme', provider: 'Enel Green Power RSA', eligibility: ['South African citizen from one of the published project areas', 'Grade 12 or current tertiary student in an eligible TVET, diploma or degree route', 'Academic merit and financial need'], coverage: ['Individually determined tuition', 'Registration', 'Accommodation', 'Meals', 'Study materials'], url: 'https://studytrust.org.za/enel-green-power-rsa-bursaries/' }
]

const southAfricaFunding = SOUTH_AFRICA_SEEDS.map((seed) => officialFunding({
  id: seed.id, name: seed.name, provider: seed.provider, providerType: 'CORPORATE', fundingType: 'CORPORATE_BURSARY',
  providerCountry: 'South Africa', eligibleDestinationCountries: ['South Africa'], domesticInternationalRules: ['DOMESTIC'],
  citizenshipRules: ['South Africa'], residenceRules: ['South Africa'], eligibleStudyAreas: seed.areas ?? [], otherEligibility: seed.eligibility,
  amountType: seed.name.includes('Investec') ? 'FULL_COST' : 'VARIABLE', coverage: seed.coverage, applicationOpensAt: '2026-06-01',
  applicationDeadline: '2026-09-30', officialUrl: seed.url, fundingCycle: '2027', cycleStatus: 'OPEN', active: true
}))

const AUSTRALIA_SEEDS: FundingSeed[] = [
  { id: 'unimelb-chancellors-current', name: "Melbourne Chancellor's Scholarship", provider: 'University of Melbourne', providerType: 'UNIVERSITY', fundingType: 'MERIT_SCHOLARSHIP', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], eligibleInstitutions: ['unimelb'], domesticInternationalRules: ['DOMESTIC'], amountType: 'RANGE', fundingAmount: 17500, fundingAmountMax: 32500, currency: 'AUD', coverage: ['Published benefit range plus Commonwealth Supported Place student-contribution sponsorship'], officialUrl: 'https://scholarships.unimelb.edu.au/awards/melbourne-chancellors-scholarship', fundingCycle: 'Current cycle', cycleStatus: 'OPEN', active: true, separateApplicationRequired: false, otherEligibility: ['Eligible Australian or New Zealand citizen or Australian permanent resident', 'Qualifying Australian Year 12 or International Baccalaureate result'] },
  { id: 'anu-tuckwell-current', name: 'Tuckwell Scholarship Program', provider: 'Tuckwell Scholarship Program', providerType: 'FOUNDATION', fundingType: 'FOUNDATION_FUNDING', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], eligibleInstitutions: ['anu'], domesticInternationalRules: ['DOMESTIC'], amountType: 'RANGE', fundingAmount: 82800, fundingAmountMax: 138000, currency: 'AUD', coverage: ['AUD 27,600 per year at the 2026 rate for three to five years'], officialUrl: 'https://tuckwell.anu.edu.au/about/scholarship', fundingCycle: 'Current cycle details not published', cycleStatus: 'CURRENT_CYCLE_UNKNOWN', active: true },
  { id: 'uwa-fogarty-2027', name: 'UWA Fogarty Foundation Scholarship', provider: 'University of Western Australia and Fogarty Foundation', providerType: 'FOUNDATION', fundingType: 'FOUNDATION_FUNDING', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], eligibleInstitutions: ['uwa'], domesticInternationalRules: ['DOMESTIC'], amountType: 'FIXED', fundingAmount: 12500, currency: 'AUD', coverage: ['AUD 12,500 per year for the undergraduate degree'], applicationDeadline: '2026-05-15', officialUrl: 'https://www.uwa.edu.au/study/scholarships-and-fees/scholarships/uwa-fogarty-foundation', fundingCycle: '2027', cycleStatus: 'CLOSED', active: false },
  { id: 'uwa-winthrop-2027', name: 'UWA Winthrop Scholarship', provider: 'University of Western Australia', providerType: 'UNIVERSITY', fundingType: 'MERIT_SCHOLARSHIP', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], eligibleInstitutions: ['uwa'], domesticInternationalRules: ['DOMESTIC'], amountType: 'FIXED', fundingAmount: 10000, currency: 'AUD', coverage: ['AUD 10,000 per year'], applicationDeadline: '2026-06-20', officialUrl: 'https://www.uwa.edu.au/study/scholarships-and-fees/scholarships/uwa-winthrop-scholarship', fundingCycle: '2027', cycleStatus: 'CLOSED', active: false },
  { id: 'swinburne-pratt-2027', name: 'Pratt Foundation Scholarship 2027', provider: 'Pratt Foundation', providerType: 'FOUNDATION', fundingType: 'FOUNDATION_FUNDING', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], eligibleInstitutions: ['swinburne'], domesticInternationalRules: ['DOMESTIC'], amountType: 'FIXED', fundingAmount: 7500, currency: 'AUD', coverage: ['AUD 7,500 for one year'], applicationDeadline: '2026-10-31', officialUrl: 'https://www.swinburne.edu.au/courses/scholarships/pratt-foundation-scholarship/', fundingCycle: '2027', cycleStatus: 'OPEN', active: true },
  { id: 'swinburne-rosemary-simpson-2027', name: 'Rosemary Simpson Scholarship 2027', provider: 'Swinburne University of Technology', providerType: 'UNIVERSITY', fundingType: 'NEED_BASED_AID', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], eligibleInstitutions: ['swinburne'], domesticInternationalRules: ['DOMESTIC'], amountType: 'FIXED', fundingAmount: 50000, currency: 'AUD', coverage: ['AUD 10,000 per year for up to five years'], applicationDeadline: '2026-10-31', officialUrl: 'https://www.swinburne.edu.au/courses/scholarships/rosemary-simpson-scholarship/', fundingCycle: '2027', cycleStatus: 'OPEN', active: true },
  { id: 'swinburne-snxg-engineering-2027', name: 'SNXG Engineering Scholarships 2027', provider: 'SNXG', providerType: 'INDUSTRY', fundingType: 'INDUSTRY_BURSARY', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], eligibleInstitutions: ['swinburne'], eligibleStudyAreas: ['Engineering'], domesticInternationalRules: ['DOMESTIC', 'INTERNATIONAL'], amountType: 'RANGE', fundingAmount: 7500, fundingAmountMax: 10000, currency: 'AUD', coverage: ['One-year award based on study level'], applicationDeadline: '2026-10-31', officialUrl: 'https://www.swinburne.edu.au/courses/scholarships/snxg-engineering-scholarships/', fundingCycle: '2027', cycleStatus: 'OPEN', active: true },
  { id: 'swinburne-australia-awards-current', name: 'Australia Awards Scholarships at Swinburne', provider: 'Australian Government', providerType: 'GOVERNMENT', fundingType: 'GOVERNMENT_GRANT', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], eligibleInstitutions: ['swinburne'], domesticInternationalRules: ['INTERNATIONAL'], amountType: 'FULL_COST', coverage: ['Full-cost support under the applicable Australia Awards country agreement'], applicationDeadline: '2026-12-31', officialUrl: 'https://www.swinburne.edu.au/courses/scholarships/australia-awards-scholarships/', fundingCycle: 'Current cycle', cycleStatus: 'OPEN', active: true },
  { id: 'flinders-peter-torjul-regional-2026', name: 'The Peter Torjul Regional and Rural Student Scholarship', provider: 'Flinders University', providerType: 'UNIVERSITY', fundingType: 'UNIVERSITY_SCHOLARSHIP', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], eligibleInstitutions: ['flinders'], domesticInternationalRules: ['DOMESTIC'], amountType: 'FIXED', fundingAmount: 7500, currency: 'AUD', coverage: ['AUD 7,500 per year for up to four years'], applicationDeadline: '2026-08-19', officialUrl: 'https://www.flinders.edu.au/scholarships/the-peter-torjul-regional-and-rural-student-scholarship', fundingCycle: '2026', cycleStatus: 'CLOSED', active: false },
  { id: 'flinders-submarine-propel-2026', name: 'The Australian Submarine Propel Scholarship', provider: 'Australian Submarine Agency', providerType: 'GOVERNMENT', fundingType: 'GOVERNMENT_GRANT', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], eligibleInstitutions: ['flinders'], eligibleStudyAreas: ['Science', 'Technology', 'Engineering', 'Mathematics'], domesticInternationalRules: ['DOMESTIC'], amountType: 'FIXED', fundingAmount: 5000, currency: 'AUD', coverage: ['AUD 3,000 in May 2027 and AUD 2,000 in May 2028'], applicationDeadline: '2026-10-02', officialUrl: 'https://www.flinders.edu.au/scholarships/the_australian_submarine_propel_scholarship', fundingCycle: '2026', cycleStatus: 'OPEN', active: true },
  { id: 'uts-vc-merit-2027', name: "Vice-Chancellor's Merit Scholarship", provider: 'University of Technology Sydney', providerType: 'UNIVERSITY', fundingType: 'MERIT_SCHOLARSHIP', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], eligibleInstitutions: ['uts'], domesticInternationalRules: ['DOMESTIC'], amountType: 'FIXED', fundingAmount: 12500, currency: 'AUD', coverage: ['AUD 12,500 per year for the standard course duration'], applicationDeadline: '2026-12-07', officialUrl: 'https://www.uts.edu.au/for-students/admissions-entry/scholarships/scholarships-search/vice-chancellors-merit-scholarship', fundingCycle: '2027', cycleStatus: 'OPEN', active: true },
  { id: 'uts-vc-outstanding-2027', name: "Vice-Chancellor's Outstanding Achievement Scholarship", provider: 'University of Technology Sydney', providerType: 'UNIVERSITY', fundingType: 'MERIT_SCHOLARSHIP', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], eligibleInstitutions: ['uts'], domesticInternationalRules: ['DOMESTIC'], amountType: 'FIXED', fundingAmount: 12500, currency: 'AUD', coverage: ['AUD 12,500 per year for the standard course duration'], applicationDeadline: '2026-12-07', officialUrl: 'https://www.uts.edu.au/for-students/admissions-entry/scholarships/scholarships-search/vice-chancellors-outstanding-achievement-scholarship', fundingCycle: '2027', cycleStatus: 'OPEN', active: true },
  { id: 'uts-equal-access-current', name: 'Equal Access Scholarship', provider: 'University of Technology Sydney', providerType: 'UNIVERSITY', fundingType: 'NEED_BASED_AID', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], eligibleInstitutions: ['uts'], domesticInternationalRules: ['DOMESTIC'], amountType: 'VARIABLE', coverage: ['Equity scholarship support based on assessed disadvantage'], officialUrl: 'https://www.uts.edu.au/scholarship/equal-access-scholarship-institution-equity-scholarship', fundingCycle: 'Current cycle', cycleStatus: 'OPEN', active: true },
  { id: 'au-tertiary-access-payment', name: 'Tertiary Access Payment', provider: 'Services Australia', providerType: 'GOVERNMENT', fundingType: 'GOVERNMENT_GRANT', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], domesticInternationalRules: ['DOMESTIC'], amountType: 'UP_TO', fundingAmountMax: 5000, currency: 'AUD', coverage: ['One-off relocation payment of up to AUD 5,000'], officialUrl: 'https://www.servicesaustralia.gov.au/tertiary-access-payment', fundingCycle: 'Current rules', cycleStatus: 'OPEN', active: true },
  { id: 'au-austudy', name: 'Austudy', provider: 'Services Australia', providerType: 'GOVERNMENT', fundingType: 'GOVERNMENT_GRANT', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], domesticInternationalRules: ['DOMESTIC'], amountType: 'VARIABLE', coverage: ['Living-cost support subject to eligibility and means testing'], officialUrl: 'https://www.servicesaustralia.gov.au/austudy', fundingCycle: 'Current rules', cycleStatus: 'OPEN', active: true },
  { id: 'au-abstudy', name: 'ABSTUDY', provider: 'Services Australia', providerType: 'GOVERNMENT', fundingType: 'GOVERNMENT_GRANT', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], domesticInternationalRules: ['DOMESTIC'], amountType: 'VARIABLE', coverage: ['Study and living-cost support under the applicable ABSTUDY award'], officialUrl: 'https://www.servicesaustralia.gov.au/abstudy', fundingCycle: 'Current rules', cycleStatus: 'OPEN', active: true }
]

const CANADA_SEEDS: FundingSeed[] = [
  { id: 'utoronto-national-scholarship-2027', name: 'National Scholarship Program', provider: 'University of Toronto', providerType: 'UNIVERSITY', fundingType: 'MERIT_SCHOLARSHIP', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['utoronto'], domesticInternationalRules: ['DOMESTIC'], amountType: 'FULL_COST', coverage: ['Tuition', 'Incidental fees', 'Residence fees for up to four years'], applicationDeadline: '2026-10-30', documentDeadline: '2026-11-06', officialUrl: 'https://future.utoronto.ca/national-scholarship/about/', fundingCycle: '2027 entry', cycleStatus: 'OPEN', active: true },
  { id: 'utoronto-arbor-scholarships-2027', name: 'Arbor Scholarships', provider: 'University of Toronto', providerType: 'UNIVERSITY', fundingType: 'MERIT_SCHOLARSHIP', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['utoronto'], domesticInternationalRules: ['DOMESTIC'], amountType: 'FIXED', fundingAmount: 12000, currency: 'CAD', coverage: ['CAD 7,500 in first year and CAD 1,500 in each of the next three years'], officialUrl: 'https://future.utoronto.ca/national-scholarship/about/', fundingCycle: '2027 entry', cycleStatus: 'OPEN', active: true, separateApplicationRequired: false },
  { id: 'ubc-outstanding-international-student-2025-26', name: 'Outstanding International Student Award', provider: 'University of British Columbia', providerType: 'UNIVERSITY', fundingType: 'MERIT_SCHOLARSHIP', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['ubc'], domesticInternationalRules: ['INTERNATIONAL'], amountType: 'RANGE', fundingAmount: 10000, fundingAmountMax: 25000, currency: 'CAD', coverage: ['One-time CAD 10,000 to CAD 25,000 award'], officialUrl: 'https://you.ubc.ca/financial-planning/scholarships-awards-international-students/', fundingCycle: '2025-2026 published value', cycleStatus: 'CURRENT_CYCLE_UNKNOWN', active: true, separateApplicationRequired: false },
  { id: 'mcgill-one-year-entrance-scholarship', name: 'One-Year Entrance Scholarship', provider: 'McGill University', providerType: 'UNIVERSITY', fundingType: 'MERIT_SCHOLARSHIP', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['mcgill'], domesticInternationalRules: ['DOMESTIC', 'INTERNATIONAL'], amountType: 'FIXED', fundingAmount: 3000, currency: 'CAD', coverage: ['CAD 3,000 non-renewable entrance award'], officialUrl: 'https://www.mcgill.ca/studentaid/scholarships-aid/future-undergrads/entrance-scholarships', fundingCycle: 'Current cycle', cycleStatus: 'OPEN', active: true, renewable: false, separateApplicationRequired: false },
  { id: 'mcgill-major-entrance-scholarship', name: 'Major Entrance Scholarship', provider: 'McGill University', providerType: 'UNIVERSITY', fundingType: 'MERIT_SCHOLARSHIP', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['mcgill'], domesticInternationalRules: ['DOMESTIC', 'INTERNATIONAL'], amountType: 'RANGE', fundingAmount: 12000, fundingAmountMax: 48000, currency: 'CAD', coverage: ['CAD 3,000 to CAD 12,000 per year for up to four years'], officialUrl: 'https://www.mcgill.ca/studentaid/scholarships-aid/future-undergrads/entrance-scholarships', fundingCycle: 'Current cycle', cycleStatus: 'OPEN', active: true, renewable: true },
  { id: 'mcgill-in-course-financial-aid', name: 'In-Course Financial Aid Program', provider: 'McGill University', providerType: 'UNIVERSITY', fundingType: 'NEED_BASED_AID', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['mcgill'], domesticInternationalRules: ['DOMESTIC', 'INTERNATIONAL'], amountType: 'VARIABLE', coverage: ['In-course bursaries', 'Loans where applicable'], officialUrl: 'https://www.mcgill.ca/studentaid/scholarships-aid/current-undergrads/need', fundingCycle: 'Current cycle', cycleStatus: 'OPEN', active: true },
  { id: 'waterloo-presidents-scholarship-distinction', name: "President's Scholarship of Distinction", provider: 'University of Waterloo', providerType: 'UNIVERSITY', fundingType: 'MERIT_SCHOLARSHIP', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['waterloo'], domesticInternationalRules: ['DOMESTIC', 'INTERNATIONAL'], amountType: 'VARIABLE', coverage: ['Automatic entrance award and published distinction benefits'], officialUrl: 'https://uwaterloo.ca/future-students/financing/scholarships', fundingCycle: 'Current cycle', cycleStatus: 'OPEN', active: true, separateApplicationRequired: false },
  { id: 'waterloo-presidents-scholarship', name: "President's Scholarship", provider: 'University of Waterloo', providerType: 'UNIVERSITY', fundingType: 'MERIT_SCHOLARSHIP', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['waterloo'], domesticInternationalRules: ['DOMESTIC', 'INTERNATIONAL'], amountType: 'VARIABLE', coverage: ['Automatic entrance scholarship for the published admission-average band'], officialUrl: 'https://uwaterloo.ca/future-students/financing/scholarships', fundingCycle: 'Current cycle', cycleStatus: 'OPEN', active: true, separateApplicationRequired: false },
  { id: 'waterloo-merit-scholarship', name: 'Merit Scholarship', provider: 'University of Waterloo', providerType: 'UNIVERSITY', fundingType: 'MERIT_SCHOLARSHIP', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['waterloo'], domesticInternationalRules: ['DOMESTIC', 'INTERNATIONAL'], amountType: 'VARIABLE', coverage: ['Automatic entrance scholarship for the published admission-average band'], officialUrl: 'https://uwaterloo.ca/future-students/financing/scholarships', fundingCycle: 'Current cycle', cycleStatus: 'OPEN', active: true, separateApplicationRequired: false },
  { id: 'ualberta-national-achievement-2027', name: 'National Achievement Scholarship', provider: 'University of Alberta', providerType: 'UNIVERSITY', fundingType: 'MERIT_SCHOLARSHIP', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['ualberta'], domesticInternationalRules: ['DOMESTIC'], amountType: 'FIXED', fundingAmount: 30000, currency: 'CAD', coverage: ['CAD 30,000 over four years'], applicationDeadline: '2027-01-10', officialUrl: 'https://www.ualberta.ca/en/admissions/tuition-and-scholarships/entrance-scholarships', fundingCycle: '2027 entry', cycleStatus: 'UPCOMING', active: true },
  { id: 'ualberta-gold-standard-2027', name: 'Gold Standard Scholarship', provider: 'University of Alberta', providerType: 'UNIVERSITY', fundingType: 'MERIT_SCHOLARSHIP', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['ualberta'], domesticInternationalRules: ['DOMESTIC', 'INTERNATIONAL'], amountType: 'UP_TO', fundingAmountMax: 6000, currency: 'CAD', coverage: ['Up to CAD 6,000'], officialUrl: 'https://www.ualberta.ca/en/admissions/tuition-and-scholarships/entrance-scholarships', fundingCycle: '2027 entry', cycleStatus: 'UPCOMING', active: true, separateApplicationRequired: false },
  { id: 'ualberta-discover-award-2027', name: 'Discover University of Alberta Award', provider: 'University of Alberta', providerType: 'UNIVERSITY', fundingType: 'NEED_BASED_AID', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['ualberta'], domesticInternationalRules: ['DOMESTIC'], amountType: 'UP_TO', fundingAmountMax: 8000, currency: 'CAD', coverage: ['Up to CAD 8,000'], applicationDeadline: '2027-02-15', officialUrl: 'https://www.ualberta.ca/en/admissions/tuition-and-scholarships/entrance-scholarships', fundingCycle: '2027 entry', cycleStatus: 'UPCOMING', active: true },
  { id: 'ualberta-turtle-spirit-pathway-2027', name: 'Turtle Spirit Pathway Award for First Nations, Métis and Inuit Students', provider: 'University of Alberta', providerType: 'UNIVERSITY', fundingType: 'NEED_BASED_AID', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['ualberta'], domesticInternationalRules: ['DOMESTIC'], amountType: 'UP_TO', fundingAmountMax: 8000, currency: 'CAD', coverage: ['Up to CAD 8,000'], applicationDeadline: '2027-02-15', officialUrl: 'https://www.ualberta.ca/en/admissions/tuition-and-scholarships/entrance-scholarships/turtle-spirit-pathway-award.html', fundingCycle: '2027 entry', cycleStatus: 'UPCOMING', active: true },
  { id: 'ualberta-international-admission-scholarship', name: 'University of Alberta International Admission Scholarship', provider: 'University of Alberta', providerType: 'UNIVERSITY', fundingType: 'MERIT_SCHOLARSHIP', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['ualberta'], domesticInternationalRules: ['INTERNATIONAL'], amountType: 'UP_TO', fundingAmountMax: 10000, currency: 'CAD', coverage: ['Up to CAD 10,000'], officialUrl: 'https://www.ualberta.ca/en/admissions/tuition-and-scholarships/entrance-scholarships', fundingCycle: 'Current cycle', cycleStatus: 'OPEN', active: true, separateApplicationRequired: false },
  { id: 'ualberta-regional-excellence-scholarship', name: 'University of Alberta Regional Excellence Scholarship', provider: 'University of Alberta', providerType: 'UNIVERSITY', fundingType: 'MERIT_SCHOLARSHIP', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['ualberta'], domesticInternationalRules: ['INTERNATIONAL'], amountType: 'UP_TO', fundingAmountMax: 5000, currency: 'CAD', coverage: ['Up to CAD 5,000'], officialUrl: 'https://www.ualberta.ca/en/admissions/tuition-and-scholarships/entrance-scholarships', fundingCycle: 'Current cycle', cycleStatus: 'OPEN', active: true, separateApplicationRequired: false },
  { id: 'alberta-alexander-rutherford-2026-27', name: 'Alexander Rutherford High School Achievement Scholarship', provider: 'Government of Alberta', providerType: 'GOVERNMENT', fundingType: 'GOVERNMENT_GRANT', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], domesticInternationalRules: ['DOMESTIC'], amountType: 'UP_TO', fundingAmountMax: 2500, currency: 'CAD', coverage: ['Up to CAD 2,500'], officialUrl: 'https://studentaid.alberta.ca/scholarships-and-awards/alexander-rutherford-scholarship/', fundingCycle: '2026-2027', cycleStatus: 'OPEN', active: true },
  { id: 'dalhousie-management-promise-black-indigenous', name: 'Faculty of Management Promise Scholarship for Black and Indigenous Students', provider: 'Dalhousie University Faculty of Management', providerType: 'FACULTY', fundingType: 'FACULTY_SCHOLARSHIP', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['dalhousie'], eligibleFaculties: ['Faculty of Management'], domesticInternationalRules: ['DOMESTIC'], amountType: 'VARIABLE', coverage: ['Faculty entrance scholarship; value determined by the university'], applicationDeadline: '2027-02-15', officialUrl: 'https://www.dal.ca/admissions/scholarships-financial-aid/scholarships/future-undergraduate-student-awards.html', fundingCycle: '2027 entry', cycleStatus: 'UPCOMING', active: true }
]

export const FUNDING_SCALE_OPPORTUNITIES: FundingOpportunity[] = [
  ...southAfricaFunding,
  ...AUSTRALIA_SEEDS.map(officialFunding),
  ...CANADA_SEEDS.map(officialFunding)
]