import type { FundingOpportunity, ProgrammeCost } from './types.ts'

const CHECKED_AT = '2026-09-10T00:00:00Z'

type FundingSeed = Pick<FundingOpportunity,
  'id' | 'name' | 'provider' | 'providerType' | 'fundingType' | 'repaymentType' |
  'providerCountry' | 'eligibleDestinationCountries' | 'domesticInternationalRules' |
  'amountType' | 'coverage' | 'officialUrl' | 'applicationUrl' | 'sourceType' |
  'sourceTitle' | 'fundingCycle' | 'cycleStatus' | 'active'
> & Partial<FundingOpportunity>

function verifiedFunding(seed: FundingSeed): FundingOpportunity {
  return {
    eligibleInstitutions: [],
    eligibleProgrammes: [],
    eligibleFaculties: [],
    eligibleStudyAreas: [],
    eligibleStudyLevels: ['BACHELOR'],
    citizenshipRules: [],
    residenceRules: [],
    applicantRouteRules: [],
    curriculumRules: [],
    academicRequirements: [],
    otherEligibility: [],
    separateApplicationRequired: true,
    applicationMethod: 'Follow the official application instructions.',
    sourceUrl: seed.officialUrl,
    lastCheckedAt: CHECKED_AT,
    lastVerifiedAt: CHECKED_AT,
    confidenceStatus: 'VERIFIED_OFFICIAL',
    ...seed
  }
}

export const FUNDING_DEPTH_OPPORTUNITIES: FundingOpportunity[] = [
  verifiedFunding({ id: 'za-funza-lushaka-2026', name: 'Funza Lushaka Bursary 2026', provider: 'South African Department of Basic Education', providerType: 'GOVERNMENT', fundingType: 'BURSARY', repaymentType: 'NON_REPAYABLE', providerCountry: 'South Africa', eligibleDestinationCountries: ['South Africa'], eligibleStudyAreas: ['Education', 'Teaching'], eligibleStudyLevels: ['BACHELOR', 'CURRENT_UNIVERSITY'], citizenshipRules: ['South Africa'], residenceRules: ['South Africa'], domesticInternationalRules: ['DOMESTIC'], applicantRouteRules: ['SCHOOL_LEAVER', 'CURRENT_UNIVERSITY_NEW_UNDERGRAD'], amountType: 'VARIABLE', coverage: ['Tuition and approved study costs subject to the bursary rules'], applicationDeadline: '2026-02-01', officialUrl: 'https://www.funzalushaka.doe.gov.za/', applicationUrl: 'https://www.eservices.gov.za/', sourceType: 'government-funding', sourceTitle: 'Funza Lushaka Bursary 2026 application information', fundingCycle: '2026', cycleStatus: 'CLOSED', active: false, otherEligibility: ['First-time applicants must be 30 years or younger.', 'The bursary supports approved initial teacher education priority areas.'], applicationMethod: 'Register on the official e-Gov portal and select the Funza Lushaka Bursary Scheme.' }),
  verifiedFunding({ id: 'za-thuthuka-bursary-current', name: 'Thuthuka Bursary', provider: 'Thuthuka Education Upliftment Fund / SAICA', providerType: 'PROFESSIONAL_BODY', fundingType: 'PROFESSIONAL_BODY_FUNDING', repaymentType: 'NON_REPAYABLE', providerCountry: 'South Africa', eligibleDestinationCountries: ['South Africa'], eligibleStudyAreas: ['Accounting', 'Chartered Accountancy'], eligibleStudyLevels: ['BACHELOR', 'CURRENT_UNIVERSITY'], citizenshipRules: ['South Africa'], residenceRules: ['South Africa'], domesticInternationalRules: ['DOMESTIC'], amountType: 'VARIABLE', coverage: ['Bursary support subject to contract and annual award'], financialNeedRequirements: ['Financial need is assessed using the NSFAS means test.'], officialUrl: 'https://www.thuthukabursaryfund.co.za/', applicationUrl: 'https://www.thuthukabursaryfund.co.za/', sourceType: 'official-scholarship', sourceTitle: 'Thuthuka Bursary Application System', fundingCycle: 'Current published cycle', cycleStatus: 'CLOSED', active: false, otherEligibility: ['Only for students intending to qualify as Chartered Accountants.', 'Academic performance, NBT results and financial need are considered.'], applicationMethod: 'Apply through the official Thuthuka application system when the next cycle opens.' }),
  verifiedFunding({ id: 'za-allan-gray-fellowship-2026', name: 'Allan Gray Fellowship Programme 2026', provider: 'Allan Gray Orbis Foundation', providerType: 'FOUNDATION', fundingType: 'FOUNDATION_FUNDING', repaymentType: 'NON_REPAYABLE', providerCountry: 'South Africa', eligibleDestinationCountries: ['South Africa'], eligibleInstitutions: ['wits', 'uj', 'uct', 'nmu', 'rhodes', 'uwc', 'stellenbosch', 'up', 'ufs', 'ukzn'], eligibleStudyAreas: ['Arts', 'Humanities', 'Law', 'Health Sciences', 'Commerce', 'Engineering', 'Science'], eligibleStudyLevels: ['SCHOOL_LEAVER', 'BACHELOR', 'CURRENT_UNIVERSITY'], citizenshipRules: ['South Africa'], residenceRules: ['South Africa'], domesticInternationalRules: ['DOMESTIC'], amountType: 'VARIABLE', coverage: ['University accommodation', 'Meals', 'Textbooks and tutoring allowance', 'Monthly stipend', 'Entrepreneurial development support'], financialNeedRequirements: ['Funding level is needs-based; the published full-funding threshold is combined household income of R1 million or below.'], applicationDeadline: '2026-04-30', officialUrl: 'https://allangrayorbis.org/programmes/fellowship/', applicationUrl: 'https://allangrayorbis.org/programmes/fellowship/', sourceType: 'official-scholarship', sourceTitle: 'Allan Gray Fellowship Programme', fundingCycle: '2026', cycleStatus: 'CLOSED', active: false, otherEligibility: ['Grade 12 route requires the published academic thresholds and age limit.', 'Medicine, dentistry and veterinary science are excluded.'] }),
  verifiedFunding({ id: 'za-isfap-current', name: 'ISFAP Undergraduate Funding', provider: 'Ikusasa Student Financial Aid Programme', providerType: 'FOUNDATION', fundingType: 'BURSARY', repaymentType: 'NON_REPAYABLE', providerCountry: 'South Africa', eligibleDestinationCountries: ['South Africa'], eligibleStudyAreas: ['Actuarial Science', 'Accounting', 'Data Science', 'Engineering', 'Information Technology', 'Medicine', 'Nursing'], eligibleStudyLevels: ['BACHELOR', 'CURRENT_UNIVERSITY'], citizenshipRules: ['South Africa'], residenceRules: ['South Africa'], domesticInternationalRules: ['DOMESTIC'], amountType: 'VARIABLE', coverage: ['Bursary funding', 'Academic support', 'Career support'], financialNeedRequirements: ['ISFAP supports poor and middle-income students through its means-tested funding model.'], officialUrl: 'https://www.isfap.org.za/students', applicationUrl: 'https://www.isfap.org.za/students', sourceType: 'official-scholarship', sourceTitle: 'ISFAP funding for students', fundingCycle: 'Current cycle details not published', cycleStatus: 'CURRENT_CYCLE_UNKNOWN', active: true, otherEligibility: ['Funding focuses on approved high-demand occupations and participating programmes.'] }),

  verifiedFunding({ id: 'au-fee-help', name: 'FEE-HELP', provider: 'Australian Government', providerType: 'GOVERNMENT', fundingType: 'GOVERNMENT_STUDENT_FINANCE', repaymentType: 'REPAYABLE', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], domesticInternationalRules: ['DOMESTIC'], residenceRules: ['Australia'], amountType: 'VARIABLE', coverage: ['All or part of tuition fees for an eligible full fee-paying place'], requiredContext: ['ELIGIBLE_COURSE_OR_PLACE', 'GOVERNMENT_ELIGIBILITY'], officialUrl: 'https://www.studyassist.gov.au/financial-and-study-support/fee-help', applicationUrl: 'https://www.studyassist.gov.au/loan-application', sourceType: 'government-funding', sourceTitle: 'FEE-HELP', fundingCycle: 'Current rules', cycleStatus: 'OPEN', active: true, otherEligibility: ['The provider and course must offer FEE-HELP.', 'Citizenship, residence, HELP balance, USI and genuine-student rules apply.'], applicationMethod: 'Submit the provider electronic Commonwealth Assistance Form by the census date.' }),
  verifiedFunding({ id: 'au-youth-allowance-students', name: 'Youth Allowance for students', provider: 'Services Australia', providerType: 'GOVERNMENT', fundingType: 'GOVERNMENT_GRANT', repaymentType: 'NON_REPAYABLE', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], domesticInternationalRules: ['DOMESTIC'], residenceRules: ['Australia'], eligibleStudyLevels: ['BACHELOR', 'CURRENT_UNIVERSITY'], amountType: 'VARIABLE', coverage: ['Living-cost support subject to eligibility and means testing'], officialUrl: 'https://www.servicesaustralia.gov.au/youth-allowance-for-students-and-australian-apprentices', applicationUrl: 'https://www.servicesaustralia.gov.au/how-to-claim-youth-allowance-for-students-and-apprentices', sourceType: 'government-funding', sourceTitle: 'Youth Allowance for students and Australian Apprentices', fundingCycle: 'Current rules', cycleStatus: 'OPEN', active: true, otherEligibility: ['Age, full-time study, residence, income, assets and dependency rules apply.'] }),
  verifiedFunding({ id: 'unimelb-international-undergraduate-2027', name: 'Melbourne International Undergraduate Scholarship 2027', provider: 'University of Melbourne', providerType: 'UNIVERSITY', fundingType: 'MERIT_SCHOLARSHIP', repaymentType: 'NON_REPAYABLE', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], eligibleInstitutions: ['unimelb'], domesticInternationalRules: ['INTERNATIONAL'], applicantRouteRules: ['SCHOOL_LEAVER'], amountType: 'PARTIAL_TUITION', coverage: ['20% fee remission for the duration of the course'], officialUrl: 'https://scholarships.unimelb.edu.au/awards/melbourne-international-undergraduate-scholarship', applicationUrl: 'https://study.unimelb.edu.au/how-to-apply', sourceType: 'official-scholarship', sourceTitle: 'Melbourne International Undergraduate Scholarship', fundingCycle: '2027', cycleStatus: 'OPEN', active: true, separateApplicationRequired: false, applicationMethod: 'Apply for an eligible undergraduate course; eligible applicants are considered automatically.', otherEligibility: ['Applicant must be a citizen of an eligible country under the published GDP-per-capita rule.', 'Applicant must hold an offer for an overseas-fee bachelor place and must not have previously undertaken tertiary study.'] }),
  verifiedFunding({ id: 'monash-scholarship-portfolio-current', name: 'Monash University Scholarships', provider: 'Monash University', providerType: 'UNIVERSITY', fundingType: 'UNIVERSITY_SCHOLARSHIP', repaymentType: 'NON_REPAYABLE', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], eligibleInstitutions: ['monash'], domesticInternationalRules: ['DOMESTIC', 'INTERNATIONAL'], eligibleStudyLevels: ['SCHOOL_LEAVER', 'BACHELOR', 'CURRENT_UNIVERSITY'], amountType: 'VARIABLE', coverage: ['Award value and coverage vary by scholarship'], officialUrl: 'https://www.monash.edu/study/fees-scholarships/scholarships', applicationUrl: 'https://www.monash.edu/study/fees-scholarships/scholarships', sourceType: 'official-scholarship', sourceTitle: 'Monash University scholarships', fundingCycle: 'Current cycle details vary by award', cycleStatus: 'CURRENT_CYCLE_UNKNOWN', active: true, otherEligibility: ['Citizenship, course, academic merit and financial-need rules vary by award.'], applicationMethod: 'Use the official Monash scholarship finder and follow the application instructions for the selected award.' }),

  verifiedFunding({ id: 'gb-saas-undergraduate-current', name: 'SAAS Undergraduate Funding', provider: 'Student Awards Agency Scotland', providerType: 'GOVERNMENT', fundingType: 'GOVERNMENT_STUDENT_FINANCE', repaymentType: 'MIXED', providerCountry: 'United Kingdom', eligibleDestinationCountries: ['United Kingdom'], citizenshipRules: ['United Kingdom', 'Ireland'], residenceRules: ['Scotland'], domesticInternationalRules: ['DOMESTIC'], amountType: 'VARIABLE', coverage: ['Tuition fee support', 'Student loan where eligible', 'Bursary or living-cost grant where eligible'], officialUrl: 'https://www.saas.gov.uk/full-time/undergraduates', applicationUrl: 'https://www.saas.gov.uk/full-time/undergraduates/how-to-apply', sourceType: 'government-funding', sourceTitle: 'SAAS Undergraduate funding', fundingCycle: 'Current rules', cycleStatus: 'OPEN', active: true, otherEligibility: ['Eligibility depends on ordinary residence, course, institution and personal circumstances.'] }),
  verifiedFunding({ id: 'gb-student-finance-wales-current', name: 'Student Finance Wales full-time undergraduate support', provider: 'Student Finance Wales', providerType: 'GOVERNMENT', fundingType: 'GOVERNMENT_STUDENT_FINANCE', repaymentType: 'MIXED', providerCountry: 'United Kingdom', eligibleDestinationCountries: ['United Kingdom'], citizenshipRules: ['United Kingdom', 'Ireland'], residenceRules: ['Wales'], domesticInternationalRules: ['DOMESTIC'], amountType: 'VARIABLE', coverage: ['Tuition fee support', 'Living-cost support where eligible'], officialUrl: 'https://www.studentfinancewales.co.uk/undergraduate-finance/full-time/', applicationUrl: 'https://www.studentfinancewales.co.uk/undergraduate-finance/full-time/', sourceType: 'government-funding', sourceTitle: 'Student Finance Wales full-time undergraduate finance', fundingCycle: 'Current rules', cycleStatus: 'OPEN', active: true, otherEligibility: ['Nationality, residence, course, institution and previous-study rules apply.'] }),
  verifiedFunding({ id: 'gb-student-finance-ni-current', name: 'Student Finance Northern Ireland undergraduate support', provider: 'Student Finance NI', providerType: 'GOVERNMENT', fundingType: 'GOVERNMENT_STUDENT_FINANCE', repaymentType: 'MIXED', providerCountry: 'United Kingdom', eligibleDestinationCountries: ['United Kingdom'], citizenshipRules: ['United Kingdom', 'Ireland'], residenceRules: ['Northern Ireland'], domesticInternationalRules: ['DOMESTIC'], amountType: 'VARIABLE', coverage: ['Tuition fee support', 'Living-cost support where eligible'], officialUrl: 'https://www.studentfinanceni.co.uk/types-of-finance/undergraduate/full-time/', applicationUrl: 'https://www.studentfinanceni.co.uk/types-of-finance/undergraduate/full-time/', sourceType: 'government-funding', sourceTitle: 'Student Finance NI full-time undergraduate students', fundingCycle: '2026-2027', cycleStatus: 'OPEN', active: true, otherEligibility: ['Nationality, settled-status, residence and course rules apply.'] }),
  verifiedFunding({ id: 'cambridge-trust-undergraduate', name: 'Cambridge Trust Undergraduate Scholarships', provider: 'Cambridge Commonwealth, European & International Trust', providerType: 'FOUNDATION', fundingType: 'EXTERNAL_SCHOLARSHIP', repaymentType: 'NON_REPAYABLE', providerCountry: 'United Kingdom', eligibleDestinationCountries: ['United Kingdom'], eligibleInstitutions: ['cambridge'], domesticInternationalRules: ['INTERNATIONAL'], amountType: 'VARIABLE', coverage: ['Scholarship support varies by award'], officialUrl: 'https://www.cambridgetrust.org/undergraduate-applicants/', applicationUrl: 'https://www.cambridgetrust.org/undergraduate-applicants/', sourceType: 'official-scholarship', sourceTitle: 'Cambridge Trust undergraduate applicants', fundingCycle: 'Current cycle details vary by award', cycleStatus: 'CURRENT_CYCLE_UNKNOWN', active: true, otherEligibility: ['Applicants must apply to the University of Cambridge and meet the conditions for an eligible Trust award.'] }),

  verifiedFunding({ id: 'utoronto-pearson-2027', name: 'Lester B. Pearson International Student Scholarship 2027', provider: 'University of Toronto', providerType: 'UNIVERSITY', fundingType: 'UNIVERSITY_SCHOLARSHIP', repaymentType: 'NON_REPAYABLE', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['utoronto'], domesticInternationalRules: ['INTERNATIONAL'], applicantRouteRules: ['SCHOOL_LEAVER'], amountType: 'FULL_COST', coverage: ['Tuition', 'Books', 'Incidental fees', 'Full residence support for four years'], duration: '4 years', renewable: true, applicationDeadline: '2026-11-06', documentDeadline: '2026-11-06', officialUrl: 'https://future.utoronto.ca/pearson/about/', applicationUrl: 'https://future.utoronto.ca/pearson/about/', sourceType: 'official-scholarship', sourceTitle: 'Lester B. Pearson International Student Scholarships', fundingCycle: '2027 entry', cycleStatus: 'UPCOMING', active: true, otherEligibility: ['International student requiring a Canadian study permit.', 'Final-year secondary student in 2026/2027 or graduated no earlier than June 2026.', 'School nomination is due 9 October 2026 and the U of T admission application is due 16 October 2026.'], applicationMethod: 'Obtain school nomination, apply to U of T, then use the private scholarship application link.' }),
  verifiedFunding({ id: 'ubc-imes-2027', name: 'UBC International Major Entrance Scholarship', provider: 'University of British Columbia', providerType: 'UNIVERSITY', fundingType: 'MERIT_SCHOLARSHIP', repaymentType: 'NON_REPAYABLE', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['ubc'], domesticInternationalRules: ['INTERNATIONAL'], applicantRouteRules: ['SCHOOL_LEAVER'], fundingAmount: 10000, fundingAmountMax: 25000, currency: 'CAD', amountType: 'RANGE', coverage: ['CAD 10,000 to CAD 25,000 per year for 2026/2027'], duration: 'Up to 4 years', renewable: true, officialUrl: 'https://you.ubc.ca/financial-planning/scholarships-awards-international-students/', applicationUrl: 'https://you.ubc.ca/applying-ubc/how-to-apply/', sourceType: 'official-scholarship', sourceTitle: 'International Major Entrance Scholarship', fundingCycle: '2026-2027', cycleStatus: 'OPEN', active: true, separateApplicationRequired: false, applicationMethod: 'Apply to UBC by the admission deadline; eligible international applicants are considered automatically.', otherEligibility: ['New international student entering directly from secondary school.', 'Exceptional academic achievement, intellectual promise and community involvement are considered.'] }),
  verifiedFunding({ id: 'ubc-okanagan-global-elevation-2027', name: 'UBC Okanagan Global Elevation Award 2027', provider: 'University of British Columbia', providerType: 'UNIVERSITY', fundingType: 'UNIVERSITY_SCHOLARSHIP', repaymentType: 'NON_REPAYABLE', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['ubc'], domesticInternationalRules: ['INTERNATIONAL'], fundingAmount: 8000, currency: 'CAD', amountType: 'FIXED', coverage: ['CAD 8,000 tuition credit per year'], duration: 'Up to 4 years', renewable: true, officialUrl: 'https://you.ubc.ca/financial-planning/scholarships-awards-international-students/', applicationUrl: 'https://you.ubc.ca/applying-ubc/how-to-apply/', sourceType: 'official-scholarship', sourceTitle: 'UBC Okanagan Global Elevation Award', fundingCycle: '2027 entry', cycleStatus: 'OPEN', active: true, separateApplicationRequired: false, applicationMethod: 'Accept and enrol in an eligible UBC Okanagan undergraduate offer; the award is applied automatically.', otherEligibility: ['New international undergraduate student enrolling at UBC Okanagan.'] }),
  verifiedFunding({ id: 'ubc-okanagan-welcome-2027', name: 'UBC Okanagan International Welcome Award 2027', provider: 'University of British Columbia', providerType: 'UNIVERSITY', fundingType: 'UNIVERSITY_SCHOLARSHIP', repaymentType: 'NON_REPAYABLE', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['ubc'], domesticInternationalRules: ['INTERNATIONAL'], fundingAmount: 5000, currency: 'CAD', amountType: 'FIXED', coverage: ['CAD 5,000 first-year tuition credit'], duration: 'First year', officialUrl: 'https://you.ubc.ca/financial-planning/scholarships-awards-international-students/', applicationUrl: 'https://you.ubc.ca/applying-ubc/how-to-apply/', sourceType: 'official-scholarship', sourceTitle: 'UBC Okanagan International Welcome Award', fundingCycle: '2027 entry', cycleStatus: 'OPEN', active: true, separateApplicationRequired: false, applicationMethod: 'List an Okanagan degree as first choice, accept the offer and enrol full-time; the award is automatic.', otherEligibility: ['First-year international student with an Okanagan degree as first choice and a full-time course load.'] }),
  verifiedFunding({ id: 'ubc-okanagan-commerce-launch-2027', name: 'UBC Okanagan Bachelor of Commerce International Launch Award 2027', provider: 'University of British Columbia', providerType: 'FACULTY', fundingType: 'PROGRAMME_SCHOLARSHIP', repaymentType: 'NON_REPAYABLE', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['ubc'], eligibleProgrammes: ['ubc-bachelor-of-commerce'], eligibleFaculties: ['Sauder School of Business'], eligibleStudyAreas: ['Commerce'], domesticInternationalRules: ['INTERNATIONAL'], fundingAmount: 6000, currency: 'CAD', amountType: 'FIXED', coverage: ['CAD 6,000 tuition credit per year'], duration: 'Up to 4 years', renewable: true, officialUrl: 'https://you.ubc.ca/financial-planning/scholarships-awards-international-students/', applicationUrl: 'https://you.ubc.ca/applying-ubc/how-to-apply/', sourceType: 'official-scholarship', sourceTitle: 'UBC Okanagan Bachelor of Commerce International Launch Award', fundingCycle: '2027 entry', cycleStatus: 'OPEN', active: true, separateApplicationRequired: false, applicationMethod: 'Accept and enrol in the UBC Okanagan Bachelor of Commerce; the award is applied automatically.', otherEligibility: ['New international undergraduate student entering the UBC Okanagan Bachelor of Commerce in September 2027.'] }),
  verifiedFunding({ id: 'ubc-international-scholars-2027', name: 'UBC International Scholars Program 2027', provider: 'University of British Columbia', providerType: 'UNIVERSITY', fundingType: 'NEED_BASED_AID', repaymentType: 'NON_REPAYABLE', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['ubc'], domesticInternationalRules: ['INTERNATIONAL'], applicantRouteRules: ['SCHOOL_LEAVER'], amountType: 'VARIABLE', coverage: ['Meaningful financial support based on assessed need', 'Dedicated advising and scholar development'], financialNeedRequirements: ['Applicant must demonstrate significant financial need and provide official financial documents.'], applicationDeadline: '2026-11-15', documentDeadline: '2027-01-31', officialUrl: 'https://you.ubc.ca/financial-planning/scholarships-awards-international-students/international-scholars/', applicationUrl: 'https://you.ubc.ca/financial-planning/scholarships-awards-international-students/international-scholars/', sourceType: 'official-scholarship', sourceTitle: 'UBC International Scholars', fundingCycle: '2027 Winter Session', cycleStatus: 'UPCOMING', active: true, otherEligibility: ['International student entering directly from an accredited secondary school for a first undergraduate degree.', 'School or eligible non-profit nomination and teacher reference are required.', 'Published excluded programmes include nursing, dental hygiene, medical laboratory science and specified joint or dual degrees.'] }),
  verifiedFunding({ id: 'waterloo-entrance-bursary-current', name: 'Waterloo Entrance Bursary', provider: 'University of Waterloo', providerType: 'UNIVERSITY', fundingType: 'BURSARY', repaymentType: 'NON_REPAYABLE', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['waterloo'], domesticInternationalRules: ['DOMESTIC'], residenceRules: ['Ontario'], applicantRouteRules: ['SCHOOL_LEAVER'], fundingAmount: 1000, fundingAmountMax: 5000, currency: 'CAD', amountType: 'RANGE', coverage: ['CAD 1,000 to CAD 5,000 entrance bursary'], financialNeedRequirements: ['Financial need is assessed from family income and tax information.'], officialUrl: 'https://uwaterloo.ca/future-students/financing/bursaries', applicationUrl: 'https://uwaterloo.ca/future-students/applicants/portal', sourceType: 'official-scholarship', sourceTitle: 'Entrance bursaries for Ontario students', fundingCycle: 'Recurring; year not specified', cycleStatus: 'CURRENT_CYCLE_UNKNOWN', active: true, otherEligibility: ['Ontario resident entering full-time first-year study for the first time.'], applicationMethod: 'Apply through the Awards and financial aid tab in the Waterloo applicant portal.' }),

  verifiedFunding({ id: 'us-pell-grant-2026-27', name: 'Federal Pell Grant 2026-27', provider: 'US Department of Education', providerType: 'GOVERNMENT', fundingType: 'GOVERNMENT_GRANT', repaymentType: 'NON_REPAYABLE', providerCountry: 'United States', eligibleDestinationCountries: ['United States'], citizenshipRules: ['United States'], domesticInternationalRules: ['DOMESTIC'], fundingAmountMax: 7395, currency: 'USD', amountType: 'UP_TO', coverage: ['Up to USD 7,395 for the 2026-27 award year'], financialNeedRequirements: ['Usually for undergraduate students who demonstrate exceptional financial need.'], officialUrl: 'https://studentaid.gov/understand-aid/types/grants/pell', applicationUrl: 'https://studentaid.gov/h/apply-for-aid/fafsa', sourceType: 'government-funding', sourceTitle: 'Federal Pell Grants', fundingCycle: '2026-2027', cycleStatus: 'OPEN', active: true, recurring: true, otherEligibility: ['Usually requires no prior bachelor, graduate or professional degree and enrollment at an eligible nonforeign school.'], applicationMethod: 'Submit the FAFSA; the school determines eligibility and award amount.' }),
  verifiedFunding({ id: 'stanford-international-need-aid', name: 'Stanford International Undergraduate Financial Aid', provider: 'Stanford University', providerType: 'UNIVERSITY', fundingType: 'NEED_BASED_AID', repaymentType: 'NON_REPAYABLE', providerCountry: 'United States', eligibleDestinationCountries: ['United States'], eligibleInstitutions: ['stanford'], domesticInternationalRules: ['INTERNATIONAL'], amountType: 'VARIABLE', coverage: ['Institutional assistance based on family financial circumstances'], financialNeedRequirements: ['Aid is individually assessed from family financial circumstances.'], officialUrl: 'https://financialaid.stanford.edu/undergrad/how/international.html', applicationUrl: 'https://financialaid.stanford.edu/undergrad/apply/', sourceType: 'official-scholarship', sourceTitle: 'Stanford financial aid for international students', fundingCycle: 'Current admission cycle', cycleStatus: 'OPEN', active: true, otherEligibility: ['International applicants must request financial aid when applying for admission; those who do not request it cannot apply later during undergraduate study.'] }),
  verifiedFunding({ id: 'yale-international-need-aid', name: 'Yale Undergraduate Need-Based Financial Aid', provider: 'Yale University', providerType: 'UNIVERSITY', fundingType: 'NEED_BASED_AID', repaymentType: 'NON_REPAYABLE', providerCountry: 'United States', eligibleDestinationCountries: ['United States'], eligibleInstitutions: ['yale'], domesticInternationalRules: ['DOMESTIC', 'INTERNATIONAL'], amountType: 'VARIABLE', coverage: ['100% of demonstrated financial need through scholarship grants without required loans'], financialNeedRequirements: ['Aid is based on holistic assessment of income, assets, family size and circumstances.'], officialUrl: 'https://admissions.yale.edu/financial-aid-international-applicants', applicationUrl: 'https://finaid.yale.edu/apply/prospective', sourceType: 'official-scholarship', sourceTitle: 'Yale affordability and international financial aid', fundingCycle: 'Current admission cycle', cycleStatus: 'OPEN', active: true, otherEligibility: ['The same need-based policy applies regardless of citizenship or immigration status.'] }),
  verifiedFunding({ id: 'princeton-undergraduate-grant-aid-2026-27', name: 'Princeton Undergraduate Grant Aid 2026-27', provider: 'Princeton University', providerType: 'UNIVERSITY', fundingType: 'NEED_BASED_AID', repaymentType: 'NON_REPAYABLE', providerCountry: 'United States', eligibleDestinationCountries: ['United States'], eligibleInstitutions: ['princeton'], domesticInternationalRules: ['DOMESTIC', 'INTERNATIONAL'], amountType: 'VARIABLE', coverage: ['100% of demonstrated financial need with grant aid'], financialNeedRequirements: ['Princeton evaluates family resources using its institutional methodology.'], officialUrl: 'https://admission.princeton.edu/cost-aid', applicationUrl: 'https://finaid.princeton.edu/apply-aid-prospective-students', sourceType: 'official-scholarship', sourceTitle: 'Princeton Cost & Aid', fundingCycle: '2026-2027', cycleStatus: 'OPEN', active: true, otherEligibility: ['The same financial aid policy applies to international students.', 'Princeton grant aid replaces student loans in the standard aid package.'] })
]

type CostSeed = Pick<ProgrammeCost, 'id' | 'institutionId' | 'academicYear' | 'applicantType' | 'currency' | 'sourceUrl'> & Partial<ProgrammeCost>

function officialTuitionFallback(seed: CostSeed): ProgrammeCost {
  return {
    feeType: 'TUITION_ANNUAL',
    amountBasis: 'Official institution-level fee schedule or calculator; programme-specific amount not indexed',
    lastCheckedAt: CHECKED_AT,
    lastVerifiedAt: CHECKED_AT,
    confidenceStatus: 'VERIFIED_OFFICIAL',
    ...seed
  }
}

export const PROGRAMME_COST_DEPTH: ProgrammeCost[] = [
  officialTuitionFallback({ id: 'uct-fees-2027-domestic', institutionId: 'uct', academicYear: 2027, applicantType: 'DOMESTIC', currency: 'ZAR', sourceUrl: 'https://uct.ac.za/students/fees-funding' }),
  officialTuitionFallback({ id: 'uct-fees-2027-international', institutionId: 'uct', academicYear: 2027, applicantType: 'INTERNATIONAL', currency: 'ZAR', sourceUrl: 'https://uct.ac.za/students/fees-funding' }),
  officialTuitionFallback({ id: 'wits-fees-2027-domestic', institutionId: 'wits', academicYear: 2027, applicantType: 'DOMESTIC', currency: 'ZAR', sourceUrl: 'https://www.wits.ac.za/study-at-wits/fees-and-funding/' }),
  officialTuitionFallback({ id: 'wits-fees-2027-international', institutionId: 'wits', academicYear: 2027, applicantType: 'INTERNATIONAL', currency: 'ZAR', sourceUrl: 'https://www.wits.ac.za/study-at-wits/fees-and-funding/' }),
  officialTuitionFallback({ id: 'unimelb-fees-2027-domestic', institutionId: 'unimelb', academicYear: 2027, applicantType: 'DOMESTIC', placeType: 'CSP', currency: 'AUD', sourceUrl: 'https://study.unimelb.edu.au/how-to-apply/fees' }),
  officialTuitionFallback({ id: 'unimelb-fees-2027-international', institutionId: 'unimelb', academicYear: 2027, applicantType: 'INTERNATIONAL', currency: 'AUD', sourceUrl: 'https://study.unimelb.edu.au/how-to-apply/fees' }),
  officialTuitionFallback({ id: 'unsw-fees-2027-domestic', institutionId: 'unsw', academicYear: 2027, applicantType: 'DOMESTIC', placeType: 'CSP', currency: 'AUD', sourceUrl: 'https://www.unsw.edu.au/study/fees' }),
  officialTuitionFallback({ id: 'unsw-fees-2027-international', institutionId: 'unsw', academicYear: 2027, applicantType: 'INTERNATIONAL', currency: 'AUD', sourceUrl: 'https://www.unsw.edu.au/study/fees' }),
  officialTuitionFallback({ id: 'oxford-fees-2027-domestic', institutionId: 'oxford', academicYear: 2027, applicantType: 'DOMESTIC', currency: 'GBP', sourceUrl: 'https://www.ox.ac.uk/admissions/undergraduate/fees-and-funding/course-fees' }),
  officialTuitionFallback({ id: 'oxford-fees-2027-international', institutionId: 'oxford', academicYear: 2027, applicantType: 'INTERNATIONAL', currency: 'GBP', sourceUrl: 'https://www.ox.ac.uk/admissions/undergraduate/fees-and-funding/course-fees' }),
  officialTuitionFallback({ id: 'cambridge-fees-2027-domestic', institutionId: 'cambridge', academicYear: 2027, applicantType: 'DOMESTIC', currency: 'GBP', sourceUrl: 'https://www.undergraduate.study.cam.ac.uk/fees-and-finance/tuition-fees' }),
  officialTuitionFallback({ id: 'cambridge-fees-2027-international', institutionId: 'cambridge', academicYear: 2027, applicantType: 'INTERNATIONAL', currency: 'GBP', sourceUrl: 'https://www.undergraduate.study.cam.ac.uk/fees-and-finance/tuition-fees' }),
  officialTuitionFallback({ id: 'ubc-fees-2027-domestic', institutionId: 'ubc', academicYear: 2027, applicantType: 'DOMESTIC', currency: 'CAD', sourceUrl: 'https://you.ubc.ca/financial-planning/tuition-fees/' }),
  officialTuitionFallback({ id: 'ubc-fees-2027-international', institutionId: 'ubc', academicYear: 2027, applicantType: 'INTERNATIONAL', currency: 'CAD', sourceUrl: 'https://you.ubc.ca/financial-planning/tuition-fees/' }),
  officialTuitionFallback({ id: 'stanford-fees-2026-domestic', institutionId: 'stanford', academicYear: 2026, applicantType: 'DOMESTIC', currency: 'USD', sourceUrl: 'https://financialaid.stanford.edu/undergrad/budget/' }),
  officialTuitionFallback({ id: 'stanford-fees-2026-international', institutionId: 'stanford', academicYear: 2026, applicantType: 'INTERNATIONAL', currency: 'USD', sourceUrl: 'https://financialaid.stanford.edu/undergrad/budget/' }),
  officialTuitionFallback({ id: 'harvard-fees-2026-domestic', institutionId: 'harvard', academicYear: 2026, applicantType: 'DOMESTIC', currency: 'USD', sourceUrl: 'https://college.harvard.edu/financial-aid/how-aid-works' }),
  officialTuitionFallback({ id: 'harvard-fees-2026-international', institutionId: 'harvard', academicYear: 2026, applicantType: 'INTERNATIONAL', currency: 'USD', sourceUrl: 'https://college.harvard.edu/financial-aid/how-aid-works' })
]