import type { FundingCycleStatus, FundingDeadline, FundingOpportunity, ProgrammeCost } from './types.ts'
import { fundingDeadlineForOpportunity } from './funding-domain.ts'
import { FUNDING_DEPTH_OPPORTUNITIES, PROGRAMME_COST_DEPTH } from './funding-depth-data.ts'

export const FUNDING_DATA_CHECKED_AT = '2026-09-09T08:00:00Z'

const BASE_CYCLE_STATUS: Record<string, FundingCycleStatus> = {
  'za-nsfas': 'CURRENT_CYCLE_UNKNOWN',
  'au-csp': 'OPEN',
  'au-hecs-help': 'OPEN',
  'gb-student-finance-england': 'OPEN',
  'ca-student-grants-loans': 'OPEN',
  'us-federal-student-aid': 'OPEN',
  'oxford-reach-2027': 'UPCOMING',
  'harvard-need-based-aid': 'OPEN',
  'mit-need-based-scholarship': 'OPEN',
  'mcgill-entrance-scholarships': 'CURRENT_CYCLE_UNKNOWN',
  'mcgill-entrance-bursary': 'CURRENT_CYCLE_UNKNOWN',
  'unsw-scholarships-portfolio': 'CURRENT_CYCLE_UNKNOWN',
  'wits-undergraduate-funding': 'CURRENT_CYCLE_UNKNOWN',
  'utoronto-financial-aid': 'CURRENT_CYCLE_UNKNOWN'
}

const official = (opportunity: FundingOpportunity): FundingOpportunity => {
  const cycleStatus = BASE_CYCLE_STATUS[opportunity.id]
  if (!cycleStatus) throw new Error(`Missing lifecycle status for legacy funding opportunity ${opportunity.id}`)
  return { ...opportunity, cycleStatus }
}

const BASE_FUNDING_OPPORTUNITIES: FundingOpportunity[] = [
  official({ id: 'za-nsfas', name: 'NSFAS DHET Bursary Scheme', provider: 'National Student Financial Aid Scheme', providerType: 'GOVERNMENT', fundingType: 'GOVERNMENT_GRANT', repaymentType: 'NON_REPAYABLE', providerCountry: 'South Africa', eligibleDestinationCountries: ['South Africa'], eligibleInstitutions: [], eligibleProgrammes: [], eligibleFaculties: [], eligibleStudyAreas: [], eligibleStudyLevels: ['DIPLOMA', 'BACHELOR', 'CURRENT_UNIVERSITY'], citizenshipRules: ['South Africa'], residenceRules: [], domesticInternationalRules: ['DOMESTIC'], applicantRouteRules: [], curriculumRules: [], academicRequirements: [], financialNeedRequirements: ['Combined household income generally not more than R350,000 per year; disability threshold differs.'], otherEligibility: ['Study at an eligible South African public university or TVET college.', 'Previous-qualification and academic progression rules apply.'], requiredContext: ['ELIGIBLE_COURSE_OR_PLACE'], amountType: 'VARIABLE', coverage: ['Tuition', 'Accommodation subject to rules', 'Living allowance', 'Transport subject to rules', 'Learning materials'], renewable: true, separateApplicationRequired: true, applicationMethod: 'Apply through myNSFAS and verify the current cycle rules.', officialUrl: 'https://www.nsfas.org.za/content/bursary-scheme.html', applicationUrl: 'https://my.nsfas.org.za/', sourceUrl: 'https://www.nsfas.org.za/content/bursary-scheme.html', sourceType: 'government-funding', sourceTitle: 'The DHET Bursary Scheme', sourceSection: 'Who qualifies for NSFAS funding?', fundingCycle: 'Current published scheme', lastCheckedAt: FUNDING_DATA_CHECKED_AT, lastVerifiedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'VERIFIED_OFFICIAL', active: true, recurring: true }),
  official({ id: 'au-csp', name: 'Commonwealth Supported Place (CSP)', provider: 'Australian Government', providerType: 'GOVERNMENT', fundingType: 'TUITION_SUBSIDY', repaymentType: 'FEE_SUBSIDY', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], eligibleInstitutions: [], eligibleProgrammes: [], eligibleFaculties: [], eligibleStudyAreas: [], eligibleStudyLevels: ['BACHELOR', 'CURRENT_UNIVERSITY', 'HONOURS'], citizenshipRules: [], residenceRules: ['Australia'], domesticInternationalRules: ['DOMESTIC'], applicantRouteRules: [], curriculumRules: [], academicRequirements: [], otherEligibility: ['The provider must offer a CSP for the selected course.', 'Visa, residence, USI and Student Learning Entitlement rules apply.', 'Eligibility does not guarantee that a CSP will be offered.'], requiredContext: ['ELIGIBLE_COURSE_OR_PLACE', 'GOVERNMENT_ELIGIBILITY'], amountType: 'VARIABLE', coverage: ['Part of tuition through a government subsidy'], separateApplicationRequired: false, applicationMethod: 'Confirm the course has a CSP, accept the place, and submit the provider eCAF by its census date.', officialUrl: 'https://www.studyassist.gov.au/financial-and-study-support/commonwealth-supported-places-csps', applicationUrl: 'https://www.studyassist.gov.au/loan-application', sourceUrl: 'https://www.studyassist.gov.au/financial-and-study-support/commonwealth-supported-places-csps', sourceType: 'government-funding', sourceTitle: 'Commonwealth supported places (CSPs)', sourceSection: 'Eligibility for a CSP', fundingCycle: 'Current rules', lastCheckedAt: FUNDING_DATA_CHECKED_AT, lastVerifiedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'VERIFIED_OFFICIAL', active: true }),
  official({ id: 'au-hecs-help', name: 'HECS-HELP', provider: 'Australian Government', providerType: 'GOVERNMENT', fundingType: 'GOVERNMENT_STUDENT_FINANCE', repaymentType: 'REPAYABLE', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], eligibleInstitutions: [], eligibleProgrammes: [], eligibleFaculties: [], eligibleStudyAreas: [], eligibleStudyLevels: ['BACHELOR', 'CURRENT_UNIVERSITY', 'HONOURS'], citizenshipRules: [], residenceRules: ['Australia'], domesticInternationalRules: ['DOMESTIC'], applicantRouteRules: [], curriculumRules: [], academicRequirements: [], otherEligibility: ['You must be enrolled in a Commonwealth Supported Place.', 'Citizenship or eligible visa, residency, HELP balance, USI, SLE and genuine-student rules apply.'], requiredContext: ['ELIGIBLE_COURSE_OR_PLACE', 'GOVERNMENT_ELIGIBILITY'], amountType: 'VARIABLE', coverage: ['Student contribution amount for a CSP'], separateApplicationRequired: true, applicationMethod: 'Request HECS-HELP through the provider electronic Commonwealth Assistance Form by the census date.', officialUrl: 'https://www.studyassist.gov.au/financial-and-study-support/hecs-help', applicationUrl: 'https://www.studyassist.gov.au/loan-application', sourceUrl: 'https://www.studyassist.gov.au/financial-and-study-support/hecs-help', sourceType: 'government-funding', sourceTitle: 'HECS-HELP', sourceSection: 'Eligibility for a HECS-HELP loan', fundingCycle: 'Current rules', lastCheckedAt: FUNDING_DATA_CHECKED_AT, lastVerifiedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'VERIFIED_OFFICIAL', active: true }),
  official({ id: 'gb-student-finance-england', name: 'Student Finance England undergraduate support', provider: 'UK Government', providerType: 'GOVERNMENT', fundingType: 'GOVERNMENT_STUDENT_FINANCE', repaymentType: 'REPAYABLE', providerCountry: 'United Kingdom', eligibleDestinationCountries: ['United Kingdom'], eligibleInstitutions: [], eligibleProgrammes: [], eligibleFaculties: [], eligibleStudyAreas: [], eligibleStudyLevels: ['FOUNDATION', 'DIPLOMA', 'BACHELOR', 'CURRENT_UNIVERSITY'], citizenshipRules: ['United Kingdom', 'Ireland'], residenceRules: ['United Kingdom'], domesticInternationalRules: ['DOMESTIC'], applicantRouteRules: [], curriculumRules: [], academicRequirements: [], otherEligibility: ['Institution, course, previous study, age, nationality and residency rules all apply.', 'Rules differ for Scotland, Wales and Northern Ireland.'], amountType: 'VARIABLE', coverage: ['Tuition Fee Loan', 'Maintenance Loan where eligible', 'Additional grants or allowances where eligible'], separateApplicationRequired: true, applicationMethod: 'Use the official student finance eligibility checker and application service.', officialUrl: 'https://www.gov.uk/student-finance/who-qualifies', applicationUrl: 'https://www.gov.uk/student-finance/apply', sourceUrl: 'https://www.gov.uk/student-finance/who-qualifies', sourceType: 'government-funding', sourceTitle: 'Student finance for undergraduates: eligibility', fundingCycle: 'Current rules', lastCheckedAt: FUNDING_DATA_CHECKED_AT, lastVerifiedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'VERIFIED_OFFICIAL', active: true }),
  official({ id: 'ca-student-grants-loans', name: 'Canada Student Grants and Loans', provider: 'Government of Canada', providerType: 'GOVERNMENT', fundingType: 'GOVERNMENT_STUDENT_FINANCE', repaymentType: 'MIXED', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: [], eligibleProgrammes: [], eligibleFaculties: [], eligibleStudyAreas: [], eligibleStudyLevels: ['DIPLOMA', 'BACHELOR', 'CURRENT_UNIVERSITY'], citizenshipRules: ['Canada'], residenceRules: ['Canada'], domesticInternationalRules: ['DOMESTIC'], applicantRouteRules: [], curriculumRules: [], academicRequirements: [], financialNeedRequirements: ['Grant and loan assessment considers financial circumstances and provincial or territorial rules.'], otherEligibility: ['Apply through the province or territory of residence.', 'The school and programme must meet designation rules.'], amountType: 'VARIABLE', coverage: ['Tuition', 'Living expenses', 'School-related costs'], separateApplicationRequired: true, applicationMethod: 'Apply through your province or territory.', officialUrl: 'https://www.canada.ca/en/services/benefits/education/student-aid/grants-loans.html', applicationUrl: 'https://www.canada.ca/en/services/benefits/education/student-aid/grants-loans/province-apply.html', sourceUrl: 'https://www.canada.ca/en/services/benefits/education/student-aid/grants-loans.html', sourceType: 'government-funding', sourceTitle: 'Canada Student Grants and Loans', fundingCycle: 'Current rules', lastCheckedAt: FUNDING_DATA_CHECKED_AT, lastVerifiedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'VERIFIED_OFFICIAL', active: true }),
  official({ id: 'us-federal-student-aid', name: 'US Federal Student Aid', provider: 'US Department of Education', providerType: 'GOVERNMENT', fundingType: 'GOVERNMENT_STUDENT_FINANCE', repaymentType: 'MIXED', providerCountry: 'United States', eligibleDestinationCountries: ['United States'], eligibleInstitutions: [], eligibleProgrammes: [], eligibleFaculties: [], eligibleStudyAreas: [], eligibleStudyLevels: ['DIPLOMA', 'BACHELOR', 'CURRENT_UNIVERSITY'], citizenshipRules: ['United States'], residenceRules: [], domesticInternationalRules: ['DOMESTIC'], applicantRouteRules: [], curriculumRules: [], academicRequirements: [], financialNeedRequirements: ['Financial need applies to need-based aid, but there is no universal income cut-off.'], otherEligibility: ['US citizen or eligible noncitizen.', 'Enrollment in an eligible degree or certificate programme at an eligible school and other federal requirements apply.'], amountType: 'VARIABLE', coverage: ['Federal grants where eligible', 'Federal loans where eligible', 'Federal work-study where eligible'], separateApplicationRequired: true, applicationMethod: 'Complete the official FAFSA and follow the institution aid process.', officialUrl: 'https://studentaid.gov/understand-aid/eligibility', applicationUrl: 'https://studentaid.gov/h/apply-for-aid/fafsa', sourceUrl: 'https://studentaid.gov/understand-aid/eligibility', sourceType: 'government-funding', sourceTitle: 'Financial Aid Eligibility', fundingCycle: 'Current rules', lastCheckedAt: FUNDING_DATA_CHECKED_AT, lastVerifiedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'VERIFIED_OFFICIAL', active: true, recurring: true }),
  official({ id: 'oxford-reach-2027', name: 'Reach Oxford Scholarship', provider: 'University of Oxford', providerType: 'UNIVERSITY', fundingType: 'UNIVERSITY_SCHOLARSHIP', repaymentType: 'NON_REPAYABLE', providerCountry: 'United Kingdom', eligibleDestinationCountries: ['United Kingdom'], eligibleInstitutions: ['oxford'], eligibleProgrammes: [], eligibleFaculties: [], eligibleStudyAreas: [], eligibleStudyLevels: ['BACHELOR'], citizenshipRules: ['South Africa'], residenceRules: [], domesticInternationalRules: ['INTERNATIONAL'], applicantRouteRules: ['SCHOOL_LEAVER', 'GAP_YEAR'], curriculumRules: [], academicRequirements: [], financialNeedRequirements: ['Financial need is a major selection criterion.'], otherEligibility: ['Applicants need an Oxford offer before scholarship consideration.', 'All undergraduate subjects except medicine.', 'Highest academic ability, social commitment, and inability to study for a degree in the home country are considered.', 'Applicants should intend to return to their country after study.'], amountType: 'FULL_COST', coverage: ['Course fees', 'Living-cost grant', 'One return airfare per year'], duration: '3 or 4 years depending on course length', renewable: true, applicationDeadline: '2027-01-26', decisionDate: '2027-05-31', separateApplicationRequired: true, applicationMethod: 'Apply after receiving an Oxford offer using the instructions published for the 2027 cycle.', officialUrl: 'https://www.ox.ac.uk/admissions/undergraduate/fees-and-funding/oxford-support/reach-oxford-scholarship', applicationUrl: 'https://www.ox.ac.uk/admissions/undergraduate/fees-and-funding/oxford-support/reach-oxford-scholarship', sourceUrl: 'https://www.ox.ac.uk/admissions/undergraduate/fees-and-funding/oxford-support/reach-oxford-scholarship', sourceType: 'official-scholarship', sourceTitle: 'Reach Oxford Scholarship', sourceSection: 'How do I apply?', fundingCycle: '2027 entry', lastCheckedAt: FUNDING_DATA_CHECKED_AT, lastVerifiedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'VERIFIED_OFFICIAL', active: true, recurring: true }),
  official({ id: 'harvard-need-based-aid', name: 'Harvard College need-based financial aid', provider: 'Harvard College', providerType: 'UNIVERSITY', fundingType: 'NEED_BASED_AID', repaymentType: 'NON_REPAYABLE', providerCountry: 'United States', eligibleDestinationCountries: ['United States'], eligibleInstitutions: ['harvard'], eligibleProgrammes: [], eligibleFaculties: [], eligibleStudyAreas: [], eligibleStudyLevels: ['BACHELOR', 'CURRENT_UNIVERSITY'], citizenshipRules: [], residenceRules: [], domesticInternationalRules: ['DOMESTIC', 'INTERNATIONAL'], applicantRouteRules: [], curriculumRules: [], academicRequirements: [], financialNeedRequirements: ['Aid is based on demonstrated financial need considering family income, assets, expenses, size and circumstances.'], otherEligibility: ['International students are eligible for the same need-based aid as US students.', 'Harvard does not award undergraduate merit aid.'], amountType: 'VARIABLE', coverage: ['Up to 100% of demonstrated financial need'], duration: 'Reassessed for each academic year', renewable: true, separateApplicationRequired: true, applicationMethod: 'Complete Harvard’s prospective-student financial aid application requirements.', officialUrl: 'https://college.harvard.edu/financial-aid/how-aid-works', applicationUrl: 'https://college.harvard.edu/financial-aid/apply-financial-aid/prospective-students', sourceUrl: 'https://college.harvard.edu/financial-aid/how-aid-works', sourceType: 'official-scholarship', sourceTitle: 'How Aid Works', sourceSection: 'Our Principles', fundingCycle: '2026-2027', lastCheckedAt: FUNDING_DATA_CHECKED_AT, lastVerifiedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'VERIFIED_OFFICIAL', active: true, recurring: true }),
  official({ id: 'mit-need-based-scholarship', name: 'MIT need-based scholarship aid', provider: 'Massachusetts Institute of Technology', providerType: 'UNIVERSITY', fundingType: 'NEED_BASED_AID', repaymentType: 'NON_REPAYABLE', providerCountry: 'United States', eligibleDestinationCountries: ['United States'], eligibleInstitutions: ['mit'], eligibleProgrammes: [], eligibleFaculties: [], eligibleStudyAreas: [], eligibleStudyLevels: ['BACHELOR', 'CURRENT_UNIVERSITY'], citizenshipRules: [], residenceRules: [], domesticInternationalRules: ['DOMESTIC', 'INTERNATIONAL'], applicantRouteRules: [], curriculumRules: [], academicRequirements: [], financialNeedRequirements: ['Aid is individually assessed from family financial circumstances.'], otherEligibility: ['MIT states undergraduate admission is need-blind and full-need for domestic and international students.'], amountType: 'VARIABLE', coverage: ['Demonstrated financial need'], duration: 'Reassessed for each academic year', renewable: true, separateApplicationRequired: true, applicationMethod: 'Follow MIT Student Financial Services application instructions.', officialUrl: 'https://sfs.mit.edu/undergraduate-students/the-cost-of-attendance/making-mit-affordable/', applicationUrl: 'https://sfs.mit.edu/undergraduate-students/apply-for-aid/', sourceUrl: 'https://sfs.mit.edu/undergraduate-students/the-cost-of-attendance/making-mit-affordable/', sourceType: 'official-scholarship', sourceTitle: 'Making MIT affordable', sourceSection: 'Meeting the needs of all students', fundingCycle: '2026-2027', lastCheckedAt: FUNDING_DATA_CHECKED_AT, lastVerifiedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'VERIFIED_OFFICIAL', active: true, recurring: true }),
  official({ id: 'mcgill-entrance-scholarships', name: 'McGill Entrance Scholarship Program', provider: 'McGill University', providerType: 'UNIVERSITY', fundingType: 'MERIT_SCHOLARSHIP', repaymentType: 'NON_REPAYABLE', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['mcgill'], eligibleProgrammes: [], eligibleFaculties: [], eligibleStudyAreas: [], eligibleStudyLevels: ['SCHOOL_LEAVER', 'BACHELOR'], citizenshipRules: [], residenceRules: [], domesticInternationalRules: ['DOMESTIC', 'INTERNATIONAL'], applicantRouteRules: ['SCHOOL_LEAVER'], curriculumRules: [], academicRequirements: [], otherEligibility: ['For newly accepted first-year, first-degree undergraduate students entering from high school or CEGEP.', 'Academic excellence criteria apply.'], amountType: 'VARIABLE', coverage: ['One-year or renewable entrance scholarship'], renewable: true, separateApplicationRequired: false, applicationMethod: 'Review the merit-based entrance scholarship instructions and award calendar.', officialUrl: 'https://www.mcgill.ca/studentaid/scholarships-aid/future-undergrads', applicationUrl: 'https://www.mcgill.ca/studentaid/scholarships-aid/future-undergrads/entrance-scholarships', sourceUrl: 'https://www.mcgill.ca/studentaid/scholarships-aid/future-undergrads', sourceType: 'official-scholarship', sourceTitle: 'Future Undergraduates', sourceSection: 'Financial Support for High School & CEGEP Students', fundingCycle: 'Current entry cycle', lastCheckedAt: FUNDING_DATA_CHECKED_AT, lastVerifiedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'VERIFIED_OFFICIAL', active: true, recurring: true }),
  official({ id: 'mcgill-entrance-bursary', name: 'McGill Entrance Bursary Program', provider: 'McGill University', providerType: 'UNIVERSITY', fundingType: 'BURSARY', repaymentType: 'NON_REPAYABLE', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['mcgill'], eligibleProgrammes: [], eligibleFaculties: [], eligibleStudyAreas: [], eligibleStudyLevels: ['SCHOOL_LEAVER', 'BACHELOR'], citizenshipRules: [], residenceRules: [], domesticInternationalRules: ['DOMESTIC', 'INTERNATIONAL'], applicantRouteRules: ['SCHOOL_LEAVER'], curriculumRules: [], academicRequirements: [], financialNeedRequirements: ['For newly accepted undergraduate students from low-to-modest income families with demonstrated financial need.'], otherEligibility: ['Applicant must be newly accepted to a first-year, first-degree undergraduate programme.'], amountType: 'VARIABLE', coverage: ['Non-repayable entrance bursary'], separateApplicationRequired: true, applicationMethod: 'Use McGill’s official entrance bursary instructions.', officialUrl: 'https://www.mcgill.ca/studentaid/scholarships-aid/future-undergrads', applicationUrl: 'https://www.mcgill.ca/studentaid/scholarships-aid/future-undergrads/need', sourceUrl: 'https://www.mcgill.ca/studentaid/scholarships-aid/future-undergrads', sourceType: 'official-scholarship', sourceTitle: 'Future Undergraduates', sourceSection: 'Need-Based Funding for Undergraduate Students', fundingCycle: 'Current entry cycle', lastCheckedAt: FUNDING_DATA_CHECKED_AT, lastVerifiedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'VERIFIED_OFFICIAL', active: true, recurring: true }),
  official({ id: 'unsw-scholarships-portfolio', name: 'UNSW undergraduate scholarships and awards', provider: 'UNSW Sydney', providerType: 'UNIVERSITY', fundingType: 'UNIVERSITY_SCHOLARSHIP', repaymentType: 'NON_REPAYABLE', providerCountry: 'Australia', eligibleDestinationCountries: ['Australia'], eligibleInstitutions: ['unsw'], eligibleProgrammes: [], eligibleFaculties: [], eligibleStudyAreas: [], eligibleStudyLevels: ['SCHOOL_LEAVER', 'BACHELOR', 'CURRENT_UNIVERSITY'], citizenshipRules: [], residenceRules: [], domesticInternationalRules: ['DOMESTIC', 'INTERNATIONAL'], applicantRouteRules: [], curriculumRules: [], academicRequirements: [], otherEligibility: ['UNSW publishes separate domestic and international awards; use the official search to verify each award.'], amountType: 'VARIABLE', coverage: ['Varies by scholarship'], separateApplicationRequired: true, applicationMethod: 'Search the official scholarship portfolio; some awards are automatic and others require a separate application.', officialUrl: 'https://www.unsw.edu.au/study/how-to-apply/scholarships', applicationUrl: 'https://www.scholarships.unsw.edu.au/scholarships/search', sourceUrl: 'https://www.unsw.edu.au/study/how-to-apply/scholarships', sourceType: 'official-scholarship', sourceTitle: 'Scholarships & Awards', fundingCycle: 'Current entry cycle', lastCheckedAt: FUNDING_DATA_CHECKED_AT, lastVerifiedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'VERIFIED_OFFICIAL', active: true, recurring: true }),
  official({ id: 'wits-undergraduate-funding', name: 'Wits undergraduate scholarships and bursaries', provider: 'University of the Witwatersrand', providerType: 'UNIVERSITY', fundingType: 'BURSARY', repaymentType: 'UNKNOWN', providerCountry: 'South Africa', eligibleDestinationCountries: ['South Africa'], eligibleInstitutions: ['wits'], eligibleProgrammes: [], eligibleFaculties: [], eligibleStudyAreas: [], eligibleStudyLevels: ['BACHELOR', 'CURRENT_UNIVERSITY'], citizenshipRules: [], residenceRules: [], domesticInternationalRules: [], applicantRouteRules: [], curriculumRules: [], academicRequirements: [], otherEligibility: ['Wits administers university, donor and external-sponsor funding; each award has its own rules and direct application process.'], amountType: 'VARIABLE', coverage: ['Varies by bursary or scholarship'], separateApplicationRequired: true, applicationMethod: 'Open the Wits undergraduate scholarships and bursaries list, then apply directly as instructed by the named funder.', officialUrl: 'https://www.wits.ac.za/study-at-wits/financial-aid-and-scholarships-administration/scholarships-and-bursaries/', applicationUrl: 'https://www.wits.ac.za/study-at-wits/financial-aid-and-scholarships-administration/scholarships-and-bursaries/', sourceUrl: 'https://www.wits.ac.za/study-at-wits/financial-aid-and-scholarships-administration/', sourceType: 'official-scholarship', sourceTitle: 'Financial Aid and Scholarships Administration', sourceSection: 'Scholarships and Bursaries: Undergraduate', fundingCycle: 'Current listings', lastCheckedAt: FUNDING_DATA_CHECKED_AT, lastVerifiedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'VERIFIED_OFFICIAL', active: true, recurring: true }),
  official({ id: 'utoronto-financial-aid', name: 'University of Toronto financial aid', provider: 'University of Toronto', providerType: 'UNIVERSITY', fundingType: 'NEED_BASED_AID', repaymentType: 'MIXED', providerCountry: 'Canada', eligibleDestinationCountries: ['Canada'], eligibleInstitutions: ['utoronto'], eligibleProgrammes: [], eligibleFaculties: [], eligibleStudyAreas: [], eligibleStudyLevels: ['BACHELOR', 'CURRENT_UNIVERSITY'], citizenshipRules: [], residenceRules: [], domesticInternationalRules: ['DOMESTIC', 'INTERNATIONAL'], applicantRouteRules: [], curriculumRules: [], academicRequirements: [], financialNeedRequirements: ['Available support depends on residence, citizenship and individual financial circumstances.'], otherEligibility: ['Canadian, US and other international applicants use different official financial-aid pathways.'], amountType: 'VARIABLE', coverage: ['Student awards', 'Government aid where eligible', 'Other financial resources'], separateApplicationRequired: true, applicationMethod: 'Choose the official financial-aid pathway matching your citizenship and residence.', officialUrl: 'https://future.utoronto.ca/finances/financial-aid/', applicationUrl: 'https://future.utoronto.ca/finances/financial-aid/', sourceUrl: 'https://future.utoronto.ca/finances/financial-aid/', sourceType: 'official-scholarship', sourceTitle: 'Financial Aid', fundingCycle: 'Current entry cycle', lastCheckedAt: FUNDING_DATA_CHECKED_AT, lastVerifiedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'VERIFIED_OFFICIAL', active: true, recurring: true })
]

export const FUNDING_OPPORTUNITIES: FundingOpportunity[] = [...BASE_FUNDING_OPPORTUNITIES, ...FUNDING_DEPTH_OPPORTUNITIES]

export const FUNDING_DEADLINES: FundingDeadline[] = FUNDING_OPPORTUNITIES.flatMap((opportunity) => {
  const deadline = fundingDeadlineForOpportunity(opportunity)
  return deadline ? [deadline] : []
})

export const PROGRAMME_COSTS: ProgrammeCost[] = [
  { id: 'mit-undergraduate-tuition-2026', institutionId: 'mit', academicYear: 2026, applicantType: 'DOMESTIC', feeType: 'TUITION_ANNUAL', amount: 66720, currency: 'USD', amountBasis: '2026-2027 annual tuition before aid', additionalCosts: 'Separate student life, housing, food, books, personal and insurance costs may apply.', sourceUrl: 'https://sfs.mit.edu/undergraduate-students/the-cost-of-attendance/annual-student-budget/', lastCheckedAt: FUNDING_DATA_CHECKED_AT, lastVerifiedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'VERIFIED_OFFICIAL' },
  { id: 'mit-international-tuition-2026', institutionId: 'mit', academicYear: 2026, applicantType: 'INTERNATIONAL', feeType: 'TUITION_ANNUAL', amount: 66720, currency: 'USD', amountBasis: '2026-2027 annual tuition before aid', additionalCosts: 'Separate student life, housing, food, books, personal and insurance costs may apply.', sourceUrl: 'https://sfs.mit.edu/undergraduate-students/the-cost-of-attendance/annual-student-budget/', lastCheckedAt: FUNDING_DATA_CHECKED_AT, lastVerifiedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'VERIFIED_OFFICIAL' },
  { id: 'monash-fees-not-indexed-domestic', institutionId: 'monash', academicYear: 2027, applicantType: 'DOMESTIC', placeType: 'CSP', feeType: 'TUITION_ANNUAL', currency: 'AUD', amountBasis: 'Course-specific fee not indexed', sourceUrl: 'https://www.monash.edu/study/fees-scholarships/fees', lastCheckedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'NEEDS_REVIEW' },
  { id: 'monash-fees-not-indexed-international', institutionId: 'monash', academicYear: 2027, applicantType: 'INTERNATIONAL', feeType: 'TUITION_ANNUAL', currency: 'AUD', amountBasis: 'Course-specific fee not indexed', sourceUrl: 'https://www.monash.edu/study/fees-scholarships/fees', lastCheckedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'NEEDS_REVIEW' },
  { id: 'utoronto-fees-not-indexed-domestic', institutionId: 'utoronto', academicYear: 2027, applicantType: 'DOMESTIC', feeType: 'TUITION_ANNUAL', currency: 'CAD', amountBasis: 'Programme, year, load and campus-specific fee not indexed', sourceUrl: 'https://future.utoronto.ca/fees/', lastCheckedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'VERIFIED_OFFICIAL' },
  { id: 'utoronto-fees-not-indexed-international', institutionId: 'utoronto', academicYear: 2027, applicantType: 'INTERNATIONAL', feeType: 'TUITION_ANNUAL', currency: 'CAD', amountBasis: 'Programme, year, load and campus-specific fee not indexed', sourceUrl: 'https://future.utoronto.ca/fees/', lastCheckedAt: FUNDING_DATA_CHECKED_AT, confidenceStatus: 'VERIFIED_OFFICIAL' },
  ...PROGRAMME_COST_DEPTH
]

export function getFundingOpportunity(id: string) {
  return FUNDING_OPPORTUNITIES.find((opportunity) => opportunity.id === id)
}

export function getFundingForProgramme(institutionId: string, programmeId: string, studyAreas: string[]) {
  return FUNDING_OPPORTUNITIES.filter((opportunity) =>
    (!opportunity.eligibleInstitutions.length || opportunity.eligibleInstitutions.includes(institutionId)) &&
    (!opportunity.eligibleProgrammes.length || opportunity.eligibleProgrammes.includes(programmeId)) &&
    (!opportunity.eligibleStudyAreas.length || studyAreas.some((area) => opportunity.eligibleStudyAreas.includes(area)))
  )
}

export function getFundingDiagnostics(now = new Date()) {
  const within30Days = FUNDING_DEADLINES.filter((deadline) => {
    const days = (new Date(`${deadline.dueAt}T23:59:59Z`).getTime() - now.getTime()) / 86_400_000
    return days >= 0 && days <= 30
  }).length
  return {
    active: FUNDING_OPPORTUNITIES.filter((opportunity) => opportunity.active).length,
    closed: FUNDING_OPPORTUNITIES.filter((opportunity) => !opportunity.active || (opportunity.applicationDeadline && new Date(`${opportunity.applicationDeadline}T23:59:59Z`) < now)).length,
    deadlinesWithin30Days: within30Days,
    stale: FUNDING_OPPORTUNITIES.filter((opportunity) => opportunity.confidenceStatus === 'STALE').length,
    conflicts: FUNDING_OPPORTUNITIES.filter((opportunity) => opportunity.confidenceStatus === 'CONFLICTING').length,
    byCountry: Object.fromEntries(['South Africa', 'Australia', 'United Kingdom', 'Canada', 'United States'].map((country) => [country, FUNDING_OPPORTUNITIES.filter((opportunity) => opportunity.providerCountry === country).length]))
  }
}