'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import { ArrowLeft, CalendarPlus, Check, ExternalLink } from 'lucide-react'
import { useAuth } from '@/components/auth-provider'
import { FundingNavigation } from '@/components/universities/funding-navigation'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { createFundingDeadlineTask, fundingPlannerPayload, validHttpsUrl } from '@/lib/universities/funding-domain'
import { FUNDING_DEADLINES, getFundingOpportunity } from '@/lib/universities/funding-data'
import { universityStorage } from '@/lib/universities/storage'
import type { ApplicationDocument, ApplicationTask, FundingApplication, FundingApplicationStatus } from '@/lib/universities/types'

const statuses: FundingApplicationStatus[] = ['INTERESTED', 'SAVED', 'PREPARING', 'READY', 'SUBMITTED', 'AWAITING_DECISION', 'INTERVIEW', 'AWARDED', 'PARTIALLY_AWARDED', 'UNSUCCESSFUL', 'ACCEPTED', 'DECLINED', 'WITHDRAWN']
const documentStatuses: ApplicationDocument['status'][] = ['NOT_STARTED', 'REQUESTED', 'READY', 'UPLOADED', 'SUBMITTED', 'NOT_REQUIRED']
const label = (value: string) => value.toLowerCase().replace(/_/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())

export default function FundingApplicationPage() {
  const { applicationId } = useParams<{ applicationId: string }>()
  const { isGuest, settings, saveSettings } = useAuth()
  const [application, setApplication] = useState<FundingApplication | null>(null)
  const [uploads, setUploads] = useState<Array<{ id: string; filename: string }>>([])
  const [message, setMessage] = useState('')
  const [urlDraft, setUrlDraft] = useState('')
  useEffect(() => { const items = isGuest ? universityStorage.getFundingApplications() : settings.fundingApplications; const loaded = items.find((item) => item.id === applicationId) ?? null; setApplication(loaded); setUrlDraft(loaded?.applicationUrlOverride || '') }, [applicationId, isGuest, settings.fundingApplications])
  useEffect(() => { if (isGuest) return; void fetch('/api/app-state/documents?sort=newest&limit=1000', { cache: 'no-store' }).then((response) => response.json()).then((payload) => setUploads(Array.isArray(payload.documents) ? payload.documents : [])).catch(() => setUploads([])) }, [isGuest])
  const persist = (next: FundingApplication) => { const items = isGuest ? universityStorage.getFundingApplications() : settings.fundingApplications; const nextItems = items.map((item) => item.id === next.id ? next : item); if (isGuest) universityStorage.saveFundingApplications(nextItems); else void saveSettings({ fundingApplications: nextItems }); setApplication(next) }
  const update = (updates: Partial<FundingApplication>) => application && persist({ ...application, ...updates, updatedAt: new Date().toISOString() })
  if (!application) return <main className="mx-auto max-w-4xl px-4 py-10"><Card><h1 className="text-xl font-semibold">Funding application not found</h1><Link href="/universities/funding/applications" className="mt-4 inline-flex text-sky-700">Return to applications</Link></Card></main>
  const opportunity = application.fundingOpportunityId ? getFundingOpportunity(application.fundingOpportunityId) : undefined
  const officialDeadline = opportunity ? FUNDING_DEADLINES.find((deadline) => deadline.fundingOpportunityId === opportunity.id) : undefined
  const name = opportunity?.name || application.customOpportunityName || 'Untitled funding'
  const dueAt = application.deadlineOverride || officialDeadline?.dueAt
  const applicationUrl = application.applicationUrlOverride || opportunity?.applicationUrl
  const learnerEnteredUrl = Boolean(application.applicationUrlOverride)
  const addDeadlineTask = () => { if (!opportunity || !officialDeadline || application.tasks.some((task) => task.sourceDeadlineId === officialDeadline.id)) return; update({ tasks: [...application.tasks, createFundingDeadlineTask(opportunity, officialDeadline)] }) }
  const addTaskToPlanner = async (task: ApplicationTask) => { if (isGuest) { setMessage('Sign in to add this task to Planner. Your funding application remains saved on this device.'); return } if (!task.dueAt) return; const response = await fetch('/api/app-state/planner-tasks', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(fundingPlannerPayload(application, task.title, task.dueAt)) }); const result = await response.json(); if (!response.ok || !result.taskId) { setMessage(result.error || 'Could not add task to Planner.'); return } update({ tasks: application.tasks.map((item) => item.id === task.id ? { ...item, plannerTaskId: result.taskId, updatedAt: new Date().toISOString() } : item) }); setMessage('Task added to Planner.') }

  return <main className="mx-auto w-full max-w-5xl space-y-6 px-4 py-8 sm:px-6 lg:px-8"><Link href="/universities/funding/applications" className="inline-flex items-center gap-2 text-sm font-medium text-sky-700"><ArrowLeft className="h-4 w-4" />Funding applications</Link><FundingNavigation /><header><p className="text-sm font-semibold uppercase text-emerald-700">{opportunity?.provider || application.customProvider}</p><h1 className="mt-1 text-3xl font-semibold text-slate-950">{name}</h1><p className="mt-2 text-slate-600">{application.dataOrigin === 'USER_ENTERED' ? 'Learner-entered opportunity' : 'Linked to an official MuksBooks funding record'}</p></header>
    <div className="grid gap-6 lg:grid-cols-[1fr_340px]"><div className="space-y-5"><Card className="p-5"><h2 className="text-lg font-semibold text-slate-950">Application details</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Status<select value={application.status} onChange={(event) => update({ status: event.target.value as FundingApplicationStatus, submittedAt: event.target.value === 'SUBMITTED' ? application.submittedAt || new Date().toISOString() : application.submittedAt })} className="mt-1 h-10 w-full rounded-md border border-slate-300 bg-white px-3">{statuses.map((status) => <option key={status} value={status}>{label(status)}</option>)}</select></label><label className="text-sm font-medium text-slate-700">Application reference<input value={application.applicationReference || ''} onChange={(event) => update({ applicationReference: event.target.value || undefined })} className="mt-1 h-10 w-full rounded-md border border-slate-300 px-3" /></label><label className="text-sm font-medium text-slate-700">Personal deadline<input type="date" value={application.deadlineOverride || ''} onChange={(event) => update({ deadlineOverride: event.target.value || undefined })} className="mt-1 h-10 w-full rounded-md border border-slate-300 px-3" /></label><label className="text-sm font-medium text-slate-700">Currency<input maxLength={3} value={application.awardCurrency || opportunity?.currency || ''} onChange={(event) => update({ awardCurrency: event.target.value.toUpperCase() || undefined })} className="mt-1 h-10 w-full rounded-md border border-slate-300 px-3" /></label><label className="text-sm font-medium text-slate-700">Expected amount<input type="number" min="0" value={application.expectedAmount ?? ''} onChange={(event) => update({ expectedAmount: event.target.value ? Number(event.target.value) : undefined })} className="mt-1 h-10 w-full rounded-md border border-slate-300 px-3" /></label><label className="text-sm font-medium text-slate-700">Awarded amount<input type="number" min="0" value={application.awardAmount ?? ''} onChange={(event) => update({ awardAmount: event.target.value ? Number(event.target.value) : undefined })} className="mt-1 h-10 w-full rounded-md border border-slate-300 px-3" /></label></div><label className="mt-3 block text-sm font-medium text-slate-700">Notes<textarea rows={4} value={application.notes} onChange={(event) => update({ notes: event.target.value })} className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label></Card>
      <Card className="p-5"><h2 className="text-lg font-semibold text-slate-950">Application destination</h2><label className="mt-3 block text-sm font-medium text-slate-700">Learner-entered HTTPS override<input type="url" value={urlDraft} onChange={(event) => setUrlDraft(event.target.value)} onBlur={() => { const url = validHttpsUrl(urlDraft); if (urlDraft && !url) setMessage('Application links must be valid HTTPS URLs.'); else update({ applicationUrlOverride: url }) }} placeholder={opportunity?.applicationUrl || 'https://'} className="mt-1 h-10 w-full rounded-md border border-slate-300 px-3" /></label><p className="mt-2 text-xs text-slate-500">Leave blank to use the indexed official URL. Learner-entered links are not verified by MuksBooks.</p></Card>
      <Card className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold text-slate-950">Deadline and Planner</h2><p className="mt-1 text-sm text-slate-600">{dueAt || 'No deadline recorded'}</p></div>{opportunity && officialDeadline ? <Button type="button" size="sm" variant="secondary" onClick={addDeadlineTask} disabled={application.tasks.some((task) => task.sourceDeadlineId === officialDeadline.id)}><CalendarPlus className="mr-2 h-4 w-4" />Create deadline task</Button> : null}</div>{message ? <p className="mt-3 text-sm text-slate-600">{message}</p> : null}<div className="mt-4 space-y-2">{application.tasks.map((task) => <div key={task.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 pt-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={task.completed} onChange={(event) => update({ tasks: application.tasks.map((item) => item.id === task.id ? { ...item, completed: event.target.checked } : item) })} />{task.title}</label>{task.plannerTaskId ? <span className="inline-flex items-center gap-1 text-xs font-medium text-emerald-700"><Check className="h-3.5 w-3.5" />In Planner</span> : <Button type="button" size="sm" variant="outline" disabled={!task.dueAt} onClick={() => void addTaskToPlanner(task)}>Add to Planner</Button>}</div>)}</div></Card>
      <Card className="p-5"><h2 className="text-lg font-semibold text-slate-950">Document checklist</h2><p className="mt-1 text-sm text-slate-600">Link account-owned uploads; MuksBooks does not duplicate private files.</p><div className="mt-4 space-y-3">{application.documents.map((document) => <div key={document.id} className="grid gap-2 border-t border-slate-200 pt-3 sm:grid-cols-[1fr_170px]"><div><p className="text-sm font-medium text-slate-900">{document.label}</p><select value={document.uploadId || ''} disabled={isGuest} onChange={(event) => update({ documents: application.documents.map((item) => item.id === document.id ? { ...item, uploadId: event.target.value || undefined, status: event.target.value ? 'UPLOADED' : item.status } : item) })} className="mt-1 h-9 w-full rounded-md border border-slate-300 bg-white px-3 text-sm"><option value="">{isGuest ? 'Sign in to link a private upload' : 'No linked upload'}</option>{uploads.map((upload) => <option key={upload.id} value={upload.id}>{upload.filename}</option>)}</select></div><select aria-label={`${document.label} status`} value={document.status} onChange={(event) => update({ documents: application.documents.map((item) => item.id === document.id ? { ...item, status: event.target.value as ApplicationDocument['status'] } : item) })} className="h-10 rounded-md border border-slate-300 bg-white px-3">{documentStatuses.map((status) => <option key={status} value={status}>{label(status)}</option>)}</select></div>)}</div></Card></div>
      <aside className="space-y-5"><Card className="p-5"><h2 className="text-lg font-semibold text-slate-950">Application destination</h2><p className="mt-2 text-sm text-slate-600">Always confirm current eligibility and deadlines with the provider before submitting.</p>{learnerEnteredUrl ? <p className="mt-3 text-xs font-semibold uppercase text-amber-800">Learner entered · not verified</p> : opportunity ? <p className="mt-3 text-xs font-semibold uppercase text-emerald-700">Indexed official destination</p> : null}{applicationUrl ? <a href={applicationUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-sky-700">{learnerEnteredUrl ? 'Open learner-entered link' : 'Open official application'} <ExternalLink className="h-4 w-4" /></a> : <p className="mt-3 text-sm text-amber-800">No application URL recorded. Add an HTTPS destination in the tracker.</p>}</Card><Card className="p-5"><h2 className="text-lg font-semibold text-slate-950">Funding accounting</h2><p className="mt-2 text-sm text-slate-600">Expected amounts remain potential. Only an awarded or accepted amount is counted as confirmed in your Funding Plan.</p></Card></aside></div>
  </main>
}